/**
 * PONTI ARENA - Character Database
 * Centralized, data-driven character configuration.
 * Adding a new character = add one object here. No engine changes required.
 *
 * Skill effect vocabulary (consumed by combat.js / skills.js / targeting.js):
 *   type: 'damage' | 'heal' | 'buff' | 'debuff' | 'status' | 'shield' | 'special'
 *   targetType: 'single_enemy' (front-priority: nearest living row) | 'single_front' | 'single_middle' |
 *               'single_back' | 'any_enemy' (ignores row) | 'front_row' | 'middle_row' | 'back_row' |
 *               'all_enemy' | 'adjacent_enemies' (target + neighbors) |
 *               'single_ally' | 'all_ally' | 'self'
 *   power: multiplier applied to attacker.attack (for damage) or attacker.attack*0.x (for heal)
 *   statuses: [{ id, duration, chance }] status effects applied on hit
 *
 * rowSynergy: optional, purely-informational-plus-mechanical bonus this character gets while
 *   standing in a given formation row (see combat.js for where each is actually applied).
 * backlineBonus: optional flat % bonus damage this character deals when its target is in the Back Row,
 *   regardless of the attacker's own position (see combat.js).
 */

const CHARACTERS = [
  {
    id: 'knight', name: 'Knight', role: 'Tank', icon: '🛡️', color: '#8fa6c9',
    difficulty: 'Easy',
    base: { hp: 1350, attack: 95, defense: 130, speed: 70, critRate: 5, critDmg: 150 },
    description: 'A stalwart defender who shields allies at the cost of his own offense.',
    strengths: ['Very high HP', 'Very high Defense', 'Protects the team'],
    weaknesses: ['Low Speed', 'Low damage output'],
    passive: { name: 'Iron Will', desc: 'Gains +30% Defense whenever HP drops below 40%.' },
    rowSynergy: { row: 'front', stat: 'defense', percent: 20, desc: '+20% Defense while positioned in the Front Row.' },
    basicAttack: { id: 'sword_slash', name: 'Sword Slash', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'shield_bash', name: 'Shield Bash', type: 'damage', targetType: 'single_enemy', power: 1.2, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'stun', duration: 1, chance: 35 }], desc: 'Deals damage, chance to Stun.' },
    skill2: { id: 'guard', name: 'Guard', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'defense_up', duration: 2, chance: 100 }], desc: 'Sharply raises own Defense.' },
    ultimate: { id: 'royal_fortress', name: 'Royal Fortress', type: 'shield', targetType: 'all_ally', power: 0.46, desc: 'Shields the entire team.' },
  },
  {
    id: 'archer', name: 'Archer', role: 'Ranged', icon: '🏹', color: '#8fc98f',
    difficulty: 'Easy',
    base: { hp: 900, attack: 145, defense: 70, speed: 110, critRate: 20, critDmg: 165 },
    description: 'A precise marksman who punishes high-HP targets with crippling shots.',
    strengths: ['High Speed', 'Strong single-target damage'],
    weaknesses: ['Low HP', 'Low Defense'],
    passive: { name: 'Eagle Eye', desc: '+10% Critical Chance against targets above 50% HP.' },
    rowSynergy: { row: 'back', stat: 'critRate', percent: 15, desc: '+15% Critical Chance while positioned in the Back Row.' },
    basicAttack: { id: 'arrow_shot', name: 'Arrow Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'charged_arrow', name: 'Charged Arrow', type: 'damage', targetType: 'single_back', power: 1.4, cooldown: 2, energyGain: 15, desc: 'Piercing shot aimed at the enemy Back Row.' },
    skill2: { id: 'multi_shot', name: 'Multi Shot', type: 'damage', targetType: 'all_enemy', power: 0.75, cooldown: 3, energyGain: 15, desc: 'Fires at every enemy.' },
    ultimate: { id: 'rain_of_arrows', name: 'Rain of Arrows', type: 'damage', targetType: 'all_enemy', power: 1.22, desc: 'A devastating volley on all enemies.' },
  },
  {
    id: 'wizard', name: 'Wizard', role: 'Mage', icon: '🧙', color: '#b18fe0',
    difficulty: 'Normal',
    base: { hp: 850, attack: 155, defense: 65, speed: 90, critRate: 12, critDmg: 160 },
    description: 'A scholar of the arcane whose spells snowball in power the more he casts.',
    strengths: ['Very high burst', 'Scales with skill usage'],
    weaknesses: ['Low HP', 'Low Speed'],
    passive: { name: 'Arcane Mastery', desc: 'Each consecutive skill cast (not basic attack) grants +10% damage, stacking up to 3 times.' },
    basicAttack: { id: 'arcane_bolt', name: 'Arcane Bolt', type: 'damage', targetType: 'single_enemy', power: 0.9, energyGain: 10 },
    skill1: { id: 'fireball', name: 'Fireball', type: 'damage', targetType: 'single_enemy', power: 1.5, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'burn', duration: 2, chance: 60 }], desc: 'Deals damage and may Burn the target.' },
    skill2: { id: 'arcane_burst', name: 'Arcane Burst', type: 'damage', targetType: 'all_enemy', power: 0.9, cooldown: 3, energyGain: 15, desc: 'An explosion hitting all enemies.' },
    ultimate: { id: 'meteor', name: 'Meteor', type: 'damage', targetType: 'adjacent_enemies', power: 1.15, desc: 'Calls down a meteor on a target and its adjacent enemies.' },
  },
  {
    id: 'assassin', name: 'Assassin', role: 'Assassin', icon: '🗡️', color: '#c96b6b',
    difficulty: 'Hard',
    base: { hp: 780, attack: 165, defense: 55, speed: 118, critRate: 25, critDmg: 190 },
    description: 'A shadow-blade that finishes weakened targets in a single strike.',
    strengths: ['Extreme burst on low-HP targets', 'Very high Speed'],
    weaknesses: ['Very low HP', 'Very low Defense'],
    passive: { name: 'Killing Instinct', desc: '+35% damage against targets below 30% HP.' },
    backlineBonus: { percent: 30, desc: 'Shadow Hunter: +30% damage against enemies positioned in the Back Row.' },
    basicAttack: { id: 'dagger_strike', name: 'Dagger Strike', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'shadow_step', name: 'Shadow Step', type: 'damage', targetType: 'single_back', power: 1.3, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'defense_down', duration: 2, chance: 70 }], desc: 'Strikes and lowers target Defense.' },
    skill2: { id: 'poison_blade', name: 'Poison Blade', type: 'damage', targetType: 'single_enemy', power: 0.9, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'poison', duration: 3, chance: 90 }], desc: 'Poisons the target.' },
    ultimate: { id: 'death_mark', name: 'Death Mark', type: 'damage', targetType: 'single_enemy', power: 2.6, statuses: [{ id: 'mark', duration: 2, chance: 100 }], desc: 'A lethal finishing blow that Marks the target.' },
  },
  {
    id: 'berserker', name: 'Berserker', role: 'Fighter', icon: '🪓', color: '#d18a4a',
    difficulty: 'Normal',
    base: { hp: 1150, attack: 150, defense: 90, speed: 95, critRate: 15, critDmg: 170 },
    description: 'The lower his HP falls, the harder he hits.',
    strengths: ['Damage scales as HP drops', 'Durable bruiser'],
    weaknesses: ['Weak while at full HP', 'No mitigation'],
    passive: { name: 'Fury', desc: 'Gains up to +40% Attack as HP decreases (max at 20% HP).' },
    basicAttack: { id: 'heavy_axe', name: 'Heavy Axe', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'rage_strike', name: 'Rage Strike', type: 'damage', targetType: 'single_enemy', power: 1.4, cooldown: 2, energyGain: 20, desc: 'A furious blow that generates extra Energy.' },
    skill2: { id: 'blood_frenzy', name: 'Blood Frenzy', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }], desc: 'Raises own Attack.' },
    ultimate: { id: 'berserker_rage', name: 'Berserker Rage', type: 'damage', targetType: 'all_enemy', power: 1.3, desc: 'A wide cleave against all enemies.' },
  },
  {
    id: 'cleric', name: 'Cleric', role: 'Support', icon: '✨', color: '#e0d68f',
    difficulty: 'Easy',
    base: { hp: 950, attack: 75, defense: 80, speed: 88, critRate: 8, critDmg: 150 },
    description: 'A healer whose blessings keep the team standing.',
    strengths: ['High single-target healing', 'Cleanses debuffs'],
    weaknesses: ['Very low damage', 'Low Speed'],
    passive: { name: 'Holy Aura', desc: 'Allies regenerate 2% max HP at the start of their turn.' },
    rowSynergy: { row: 'back', stat: 'healPower', percent: 20, desc: '+20% Healing Done while positioned in the Back Row.' },
    basicAttack: { id: 'holy_strike', name: 'Holy Strike', type: 'damage', targetType: 'single_enemy', power: 0.8, energyGain: 10 },
    skill1: { id: 'heal', name: 'Heal', type: 'heal', targetType: 'single_ally', power: 1.6, cooldown: 2, energyGain: 15, desc: 'Restores HP to one ally.' },
    skill2: { id: 'purify', name: 'Purify', type: 'special', targetType: 'single_ally', power: 0, cooldown: 3, energyGain: 15, cleanse: true, desc: 'Removes all debuffs from an ally.' },
    ultimate: { id: 'divine_blessing', name: 'Divine Blessing', type: 'heal', targetType: 'all_ally', power: 1.1, desc: 'Heals the entire team.' },
  },
  {
    id: 'ranger', name: 'Ranger', role: 'Ranged', icon: '🎯', color: '#7fbf8f',
    difficulty: 'Normal',
    base: { hp: 980, attack: 135, defense: 78, speed: 105, critRate: 18, critDmg: 160 },
    description: 'A trapper who wears enemies down over time.',
    strengths: ['Damage-over-time pressure', 'Battlefield control'],
    weaknesses: ['Low upfront burst'],
    passive: { name: 'Hunter Instinct', desc: 'Basic Attacks against a Poisoned target deal +20% damage.' },
    basicAttack: { id: 'quick_shot', name: 'Quick Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'poison_arrow', name: 'Poison Arrow', type: 'damage', targetType: 'single_enemy', power: 1.1, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'poison', duration: 3, chance: 85 }], desc: 'Poisons the target.' },
    skill2: { id: 'trap', name: 'Trap', type: 'debuff', targetType: 'single_enemy', power: 0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'root', duration: 1, chance: 90 }, { id: 'speed_down', duration: 3, chance: 90 }], desc: 'Roots and slows the target.' },
    ultimate: { id: 'hunters_barrage', name: "Hunter's Barrage", type: 'damage', targetType: 'all_enemy', power: 1.2,
      statuses: [{ id: 'poison', duration: 3, chance: 60 }], desc: 'Strikes all enemies and may poison them.' },
  },
  {
    id: 'warlock', name: 'Warlock', role: 'Mage', icon: '💀', color: '#8a6bb0',
    difficulty: 'Hard',
    base: { hp: 870, attack: 150, defense: 62, speed: 92, critRate: 12, critDmg: 165 },
    description: 'A dark caster who trades allied life for enemy suffering.',
    strengths: ['Sustained drain damage', 'Curses reduce enemy output'],
    weaknesses: ['Fragile', 'No burst without setup'],
    passive: { name: 'Dark Pact', desc: 'Heals 15% of damage dealt by skills back to himself.' },
    basicAttack: { id: 'dark_bolt', name: 'Dark Bolt', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'curse', name: 'Curse', type: 'debuff', targetType: 'single_enemy', power: 0.6, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'attack_down', duration: 2, chance: 80 }], desc: 'Damages and weakens the target.' },
    skill2: { id: 'life_drain', name: 'Life Drain', type: 'damage', targetType: 'single_enemy', power: 1.2, cooldown: 2, energyGain: 15, drainPercent: 40, desc: 'Drains HP from the target to heal self.' },
    ultimate: { id: 'soul_harvest', name: 'Soul Harvest', type: 'damage', targetType: 'all_enemy', power: 1.5, drainPercent: 25, desc: 'Drains life from every enemy.' },
  },
  {
    id: 'ninja', name: 'Ninja', role: 'Assassin', icon: '🥷', color: '#556070',
    difficulty: 'Hard',
    base: { hp: 800, attack: 158, defense: 58, speed: 122, critRate: 22, critDmg: 175 },
    description: 'The fastest blade in the arena, gone before the counter lands.',
    strengths: ['Highest Speed in the roster', 'Evasive'],
    weaknesses: ['Low HP and Defense'],
    passive: { name: 'Evasion', desc: '15% chance to fully evade an incoming attack.' },
    basicAttack: { id: 'shuriken', name: 'Shuriken', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'shadow_dash', name: 'Shadow Dash', type: 'damage', targetType: 'single_back', power: 1.45, cooldown: 2, energyGain: 15, desc: 'A rapid strike targeting the enemy Back Row.' },
    skill2: { id: 'smoke_bomb', name: 'Smoke Bomb', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'speed_up', duration: 2, chance: 100 }], desc: 'Raises own Speed sharply.' },
    ultimate: { id: 'shadow_execution', name: 'Shadow Execution', type: 'damage', targetType: 'single_enemy', power: 2.7, desc: 'A precise, devastating finisher.' },
  },
  {
    id: 'frost-mage', name: 'Frost Mage', role: 'Mage', icon: '❄️', color: '#8fd6e0',
    difficulty: 'Normal',
    base: { hp: 880, attack: 130, defense: 68, speed: 94, critRate: 10, critDmg: 155 },
    description: 'Locks enemies down with cold, buying the team room to breathe.',
    strengths: ['Strong crowd control', 'Team-wide slows'],
    weaknesses: ['Below-average raw damage'],
    passive: { name: 'Frozen Touch', desc: 'Skills have +15% chance to apply their status effects.' },
    basicAttack: { id: 'ice_bolt', name: 'Ice Bolt', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'frost_nova', name: 'Frost Nova', type: 'damage', targetType: 'front_row', power: 0.9, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'speed_down', duration: 2, chance: 65 }], desc: 'Chills and slows the entire enemy Front Row.' },
    skill2: { id: 'ice_wall', name: 'Ice Wall', type: 'shield', targetType: 'single_ally', power: 0.5, cooldown: 3, energyGain: 15, desc: 'Shields an ally with ice.' },
    ultimate: { id: 'absolute_zero', name: 'Absolute Zero', type: 'damage', targetType: 'all_enemy', power: 1.3,
      statuses: [{ id: 'freeze', duration: 1, chance: 55 }], desc: 'May Freeze the entire enemy team, skipping their next turn.' },
  },
  {
    id: 'pyromancer', name: 'Pyromancer', role: 'Mage', icon: '🔥', color: '#e0824f',
    difficulty: 'Normal',
    base: { hp: 860, attack: 148, defense: 63, speed: 91, critRate: 14, critDmg: 165 },
    description: 'Sets the battlefield ablaze and lets fire do the rest of the work.',
    strengths: ['Strong damage-over-time', 'Area denial'],
    weaknesses: ['Fragile', 'Slow to ramp'],
    passive: { name: 'Ignition', desc: 'Damage dealt to Burning targets is increased by 20%.' },
    basicAttack: { id: 'fire_bolt', name: 'Fire Bolt', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'burning_zone', name: 'Burning Zone', type: 'damage', targetType: 'middle_row', power: 1.0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'burn', duration: 2, chance: 70 }], desc: 'Burns the entire enemy Middle Row.' },
    skill2: { id: 'flame_burst', name: 'Flame Burst', type: 'damage', targetType: 'single_enemy', power: 1.5, cooldown: 2, energyGain: 15, desc: 'A concentrated burst of flame.' },
    ultimate: { id: 'inferno', name: 'Inferno', type: 'damage', targetType: 'all_enemy', power: 1.4,
      statuses: [{ id: 'burn', duration: 3, chance: 90 }], desc: 'Engulfs all enemies in a raging inferno.' },
  },
  {
    id: 'stormcaller', name: 'Stormcaller', role: 'Mage', icon: '⚡', color: '#e0e04f',
    difficulty: 'Hard',
    base: { hp: 840, attack: 152, defense: 60, speed: 100, critRate: 16, critDmg: 170 },
    description: 'Chains lightning across the enemy formation.',
    strengths: ['Multi-target chain damage', 'Good Speed for a Mage'],
    weaknesses: ['Low HP', 'Predictable targeting'],
    passive: { name: 'Static Charge', desc: 'Each hit landed builds a charge; at 3 charges the next Basic Attack deals +50% damage.' },
    basicAttack: { id: 'lightning_bolt', name: 'Lightning Bolt', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'chain_lightning', name: 'Chain Lightning', type: 'damage', targetType: 'all_enemy', power: 0.65, cooldown: 3, energyGain: 15, desc: 'Arcs lightning across all enemies.' },
    skill2: { id: 'thunder_strike', name: 'Thunder Strike', type: 'damage', targetType: 'single_enemy', power: 1.45, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'stun', duration: 1, chance: 25 }], desc: 'A heavy bolt with a chance to Stun.' },
    ultimate: { id: 'storm_apocalypse', name: 'Storm Apocalypse', type: 'damage', targetType: 'all_enemy', power: 1.6, desc: 'A cataclysmic storm over the battlefield.' },
  },
  {
    id: 'gunslinger', name: 'Gunslinger', role: 'Ranged', icon: '🔫', color: '#c9a24f',
    difficulty: 'Hard',
    base: { hp: 920, attack: 140, defense: 72, speed: 108, critRate: 24, critDmg: 175 },
    description: 'Manages a limited Ammo pool to unleash devastating volleys.',
    strengths: ['High crit rate', 'Burst windows after Reload'],
    weaknesses: ['Ammo-limited, weak when dry'],
    passive: { name: 'Quick Draw', desc: 'The first Basic Attack each battle is guaranteed to Critical Hit.' },
    basicAttack: { id: 'shoot', name: 'Shoot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'rapid_fire', name: 'Rapid Fire', type: 'damage', targetType: 'single_back', power: 1.3, cooldown: 2, energyGain: 20, desc: 'Headshot: two quick rounds aimed at the enemy Back Row.' },
    skill2: { id: 'reload', name: 'Reload', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 20,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }], desc: 'Reloads and boosts own Attack.' },
    ultimate: { id: 'bullet_storm', name: 'Bullet Storm', type: 'damage', targetType: 'all_enemy', power: 1.35, desc: 'Empties every chamber at the enemy team.' },
  },
  {
    id: 'beastmaster', name: 'Beastmaster', role: 'Ranged', icon: '🐾', color: '#a67c52',
    difficulty: 'Hard',
    base: { hp: 1020, attack: 128, defense: 84, speed: 96, critRate: 12, critDmg: 155 },
    description: "Commands a bonded beast that fights alongside her.",
    strengths: ['Consistent extra pressure', 'Flexible commands'],
    weaknesses: ['Weaker without beast active'],
    passive: { name: 'Animal Bond', desc: "Whenever she lands an attack, her active Beast strikes the same target at the same time." },
    basicAttack: { id: 'hunter_strike', name: 'Hunter Strike', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'summon_beast', name: 'Summon Beast', type: 'special', targetType: 'self', power: 0, cooldown: 2, energyGain: 15, desc: 'Summons a bonded Beast (Tiger, Wolf, or Eagle, cycling each cast) - replaces her current Beast if she already has one. Enemies can target and kill it.' },
    skill2: { id: 'command_beast', name: 'Command Beast', type: 'special', targetType: 'any_enemy', power: 0, cooldown: 2, energyGain: 15, desc: 'Requires an active Beast: calls in reinforcements so she, her Beast, and two more animals all strike the same target together.' },
    ultimate: { id: 'primal_fury', name: 'Primal Fury', type: 'damage', targetType: 'all_enemy', power: 1.45, desc: "She and her Beast tear through the entire enemy line together." },
  },
  {
    id: 'guardian', name: 'Guardian', role: 'Tank', icon: '🏛️', color: '#7fa0c9',
    difficulty: 'Normal',
    base: { hp: 1300, attack: 100, defense: 140, speed: 65, critRate: 5, critDmg: 150 },
    description: 'An unbreakable wall who counters those foolish enough to strike him.',
    strengths: ['Highest Defense in the roster', 'Punishes attackers'],
    weaknesses: ['Lowest Speed', 'Low damage'],
    passive: { name: 'Unbreakable', desc: 'Damage taken is reduced by 10% whenever an ally has fallen.' },
    rowSynergy: { row: 'front', stat: 'defense', percent: 15, desc: '+15% Defense while positioned in the Front Row.' },
    basicAttack: { id: 'shield_strike', name: 'Shield Strike', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'fortify', name: 'Fortify', type: 'shield', targetType: 'self', power: 0.58, cooldown: 3, energyGain: 15, desc: 'Grants himself a heavy shield.' },
    skill2: { id: 'counter_guard', name: 'Counter Guard', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'counter_stance', duration: 2, chance: 100 }], desc: 'Reflects a portion of damage back at attackers.' },
    ultimate: { id: 'immortal_bastion', name: 'Immortal Bastion', type: 'shield', targetType: 'all_ally', power: 0.5, desc: 'Shields the entire team and taunts enemies.' },
  },
  {
    id: 'blood-knight', name: 'Blood Knight', role: 'Tank', icon: '🩸', color: '#a04058',
    difficulty: 'Hard',
    base: { hp: 1080, attack: 145, defense: 92, speed: 98, critRate: 14, critDmg: 165 },
    description: 'Fuels his blade with his own blood to grow stronger with every clash.',
    strengths: ['Self-sustain', 'Snowballs mid-fight'],
    weaknesses: ['Vulnerable early before stacks build'],
    passive: { name: 'Bloodlust', desc: 'Heals 20% of damage dealt by his Basic Attack.' },
    basicAttack: { id: 'blood_slash', name: 'Blood Slash', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'blood_drain', name: 'Blood Drain', type: 'damage', targetType: 'single_enemy', power: 1.2, cooldown: 2, energyGain: 15, drainPercent: 50, desc: 'Drains HP to heal himself.' },
    skill2: { id: 'crimson_rage', name: 'Crimson Rage', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }, { id: 'regeneration', duration: 2, chance: 100 }], desc: 'Boosts Attack and grants Regeneration.' },
    ultimate: { id: 'blood_apocalypse', name: 'Blood Apocalypse', type: 'damage', targetType: 'all_enemy', power: 1.5, drainPercent: 30, desc: 'A wide, life-draining strike.' },
  },
  {
    id: 'sky-lancer', name: 'Sky Lancer', role: 'Fighter', icon: '🪽', color: '#8fc9e0',
    difficulty: 'Normal',
    base: { hp: 1000, attack: 148, defense: 82, speed: 112, critRate: 18, critDmg: 168 },
    description: 'Strikes from above, diving past the front line to reach priority targets.',
    strengths: ['High mobility and Speed', 'Good damage vs backline'],
    weaknesses: ['Below-average bulk for a Fighter'],
    passive: { name: 'Aerial Mastery', desc: '+15% damage against the lowest-Defense enemy.' },
    basicAttack: { id: 'lance_strike', name: 'Lance Strike', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'sky_leap', name: 'Sky Leap', type: 'damage', targetType: 'single_enemy', power: 1.35, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'defense_down', duration: 2, chance: 60 }], desc: 'Leaps at a target, lowering its Defense.' },
    skill2: { id: 'dive_attack', name: 'Dive Attack', type: 'damage', targetType: 'single_back', power: 1.5, cooldown: 3, energyGain: 15, desc: 'Leaps past the Front Row to strike the enemy Back Row.' },
    ultimate: { id: 'heavens_spear', name: "Heaven's Spear", type: 'damage', targetType: 'all_enemy', power: 1.35, desc: 'Rains spears across the whole enemy team.' },
  },
  {
    id: 'necromancer', name: 'Necromancer', role: 'Mage', icon: '☠️', color: '#6b8a6b',
    difficulty: 'Hard',
    base: { hp: 830, attack: 140, defense: 60, speed: 88, critRate: 10, critDmg: 160 },
    description: 'Raises the dead to overwhelm the enemy with numbers and decay.',
    strengths: ['Scales with fallen units on the field', 'Strong sustained damage'],
    weaknesses: ['Weak in the early turns'],
    passive: { name: 'Necrotic Power', desc: '+5% damage for every fallen character on the battlefield (either side), plus +1% for every one of his own Skeletons that has died this battle.' },
    basicAttack: { id: 'dark_bolt_necro', name: 'Dark Bolt', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'summon_skeleton', name: 'Summon Skeleton', type: 'special', targetType: 'self', power: 0, cooldown: 1, energyGain: 15, desc: 'Raises a Skeleton onto the battlefield (HP 1, has an Attack stat) - enemies can target and kill it.' },
    skill2: { id: 'skeleton_attack', name: 'Skeleton Attack', type: 'damage', targetType: 'any_enemy', power: 1.05, cooldown: 2, energyGain: 15, desc: 'Strikes an enemy - every Skeleton still standing attacks that same target at the same time.' },
    ultimate: { id: 'dark_mass', name: 'Dark Mass', type: 'damage', targetType: 'all_enemy', power: 0.95,
      desc: 'A Dark Bolt unleashed on every enemy at once, each strike with a 40% Critical Chance.' },
  },
  {
    id: 'druid', name: 'Druid', role: 'Support', icon: '🌿', color: '#6fbf6f',
    difficulty: 'Normal',
    base: { hp: 1000, attack: 110, defense: 88, speed: 93, critRate: 10, critDmg: 155 },
    description: 'A nature warden who balances healing with punishing debuffs.',
    strengths: ['Flexible healer/controller hybrid', 'Sustained team support'],
    weaknesses: ['Low burst damage'],
    passive: { name: "Nature's Blessing", desc: 'Healing done is increased by 10%.' },
    basicAttack: { id: 'nature_strike', name: 'Nature Strike', type: 'damage', targetType: 'single_enemy', power: 0.9, energyGain: 10 },
    skill1: { id: 'regrowth', name: 'Regrowth', type: 'heal', targetType: 'single_ally', power: 1.18, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'regeneration', duration: 2, chance: 100 }], desc: 'Heals an ally and grants Regeneration.' },
    skill2: { id: 'entangling_roots', name: 'Entangling Roots', type: 'debuff', targetType: 'single_enemy', power: 0.5, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'root', duration: 1, chance: 75 }], desc: 'Roots a target in place.' },
    ultimate: { id: 'natures_wrath', name: "Nature's Wrath", type: 'heal', targetType: 'all_ally', power: 0.8,
      statuses: [{ id: 'regeneration', duration: 2, chance: 100 }], desc: 'Heals the team and grants lasting Regeneration.' },
  },
  {
    id: 'machinist', name: 'Machinist', role: 'Ranged', icon: '⚙️', color: '#c9c9a2',
    difficulty: 'Hard',
    base: { hp: 940, attack: 132, defense: 76, speed: 97, critRate: 15, critDmg: 160 },
    description: 'Deploys a real, independently-targetable Turret that joins in on every attack she lands.',
    strengths: ['Doubles up her own damage whenever the Turret is out', 'Battlefield control', 'Strong AoE Ultimate with the Turret piling on'],
    weaknesses: ['The Turret can be killed like any other unit', 'Setup-dependent', 'Loses a lot of value once the Turret is destroyed'],
    passive: { name: 'Turret Attack', desc: 'Whenever her Basic Attack lands, her Turret (if deployed) strikes the same target at the same time.' },
    basicAttack: { id: 'pistol_shot', name: 'Pistol Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'deploy_turret_mech', name: 'Deploy Turret', type: 'special', targetType: 'self', power: 0, cooldown: 4, energyGain: 15, desc: 'Deploys a Turret as a real unit on the battlefield - enemies can target and destroy it directly.' },
    skill2: { id: 'throw_mines', name: 'Throw Mines', type: 'debuff', targetType: 'single_enemy', power: 0.75, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'slow', duration: 2, chance: 85 }], desc: 'Throws a mine at the frontmost enemy, dealing damage and Slowing them - her Turret joins the strike if deployed.' },
    ultimate: { id: 'mechanical_overload', name: 'Mechanical Overload', type: 'damage', targetType: 'all_enemy', power: 1.3,
      desc: 'Opens fire on every enemy at once - her Turret joins in on all of them too, if deployed.' },
  },

  // ===================== ROSTER EXPANSION: 21-30 =====================

  {
    id: 'paladin', name: 'Paladin', role: 'Tank', icon: '✝️', color: '#e8d98a',
    difficulty: 'Hard',
    base: { hp: 1260, attack: 92, defense: 122, speed: 75, critRate: 6, critDmg: 150 },
    description: 'A holy protector who steps between danger and the ally he has sworn to guard.',
    strengths: ['Redirects damage away from a chosen ally', 'Strong sustain', 'Can prevent one lethal hit'],
    weaknesses: ['Low damage', 'Low Speed', 'Weak if he has no ally left to protect'],
    passive: { name: "Guardian's Oath", desc: 'Each turn, automatically protects the lowest-HP living ally, redirecting a capped share of the damage they take to himself. Stronger in the Front Row, weaker in the Back Row.' },
    rowSynergy: { row: 'front', stat: 'defense', percent: 15, desc: '+15% Defense while positioned in the Front Row (protection is also strongest here).' },
    basicAttack: { id: 'holy_strike_pal', name: 'Holy Strike', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'holy_shield', name: 'Holy Shield', type: 'shield', targetType: 'single_ally', power: 0.55, cooldown: 3, energyGain: 15, desc: 'Shields an ally - stronger if they are his Protected Ally.' },
    skill2: { id: 'judgment', name: 'Judgment', type: 'damage', targetType: 'single_enemy', power: 1.15, cooldown: 2, energyGain: 15, desc: 'Deals bonus damage to debuffed targets; applies a short Defense Down if they carry 2+ debuffs.' },
    ultimate: { id: 'divine_intervention', name: 'Divine Intervention', type: 'heal', targetType: 'single_ally', power: 1.3,
      statuses: [{ id: 'divine_shield', duration: 3, chance: 100 }], desc: 'Restores HP and grants a ward that prevents one lethal hit, once.' },
  },
  {
    id: 'samurai', name: 'Samurai', role: 'Fighter', icon: '⚔️', color: '#c0392b',
    difficulty: 'Master',
    base: { hp: 1010, attack: 156, defense: 85, speed: 112, critRate: 20, critDmg: 175 },
    description: 'A duelist who reads the flow of battle and punishes anyone who strikes him.',
    strengths: ['Devastating counter-attacks', 'High single-target burst', 'Rewards good prediction'],
    weaknesses: ['Weak to AoE and DoT that bypass counters', 'Punished for guessing wrong', 'Poor if constantly crowd-controlled'],
    passive: { name: 'Bushido', desc: 'If Samurai is attacked while Defending, he immediately counter-attacks (once per turn).' },
    basicAttack: { id: 'katana_slash', name: 'Katana Slash', type: 'damage', targetType: 'single_enemy', power: 1.1, energyGain: 10 },
    skill1: { id: 'iaido', name: 'Iaido', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'iaido_stance', duration: 1, chance: 100 }], desc: 'Enters a stance: a powerful counter if struck before his next turn.' },
    skill2: { id: 'parry', name: 'Parry', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'parry_stance', duration: 1, chance: 100 }, { id: 'defense_up', duration: 1, chance: 100 }], desc: 'Sharply reduces incoming damage; a successful parry marks his next attack with bonus damage.' },
    ultimate: { id: 'final_cut', name: 'Final Cut', type: 'damage', targetType: 'single_enemy', power: 2.4,
      statuses: [{ id: 'attack_down', duration: 1, chance: 0 }], desc: 'A devastating strike with bonus damage vs low-HP or Marked targets. If it fails to kill, Samurai suffers a brief Defense Down.' },
  },
  {
    id: 'vampire', name: 'Vampire', role: 'Assassin', icon: '🧛', color: '#7a1f3d',
    difficulty: 'Hard',
    base: { hp: 1130, attack: 150, defense: 88, speed: 96, critRate: 14, critDmg: 165 },
    description: 'A bloodthirsty fighter who grows harder to kill the longer the fight drags on.',
    strengths: ['Strong self-sustain on every hit', 'Scales well into long fights', 'High raw damage'],
    weaknesses: ['Vulnerable to anti-heal / healing reduction', 'Vulnerable to burst before he can stabilize', 'Vulnerable to crowd control'],
    passive: { name: 'Blood Feast', desc: 'Converts a portion of all damage he deals into HP (capped per hit so it can never spiral out of control).' },
    lifestealPercent: 16, lifestealCapPercentMaxHp: 8,
    basicAttack: { id: 'blood_claw', name: 'Blood Claw', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'crimson_bite', name: 'Crimson Bite', type: 'damage', targetType: 'single_enemy', power: 1.35, cooldown: 2, energyGain: 15, drainPercent: 30, desc: 'Bonus damage vs targets below 40% HP; heals on hit.' },
    skill2: { id: 'blood_frenzy_vamp', name: 'Blood Frenzy', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }, { id: 'blood_frenzy_def', duration: 2, chance: 100 }], desc: 'Gains Attack Up but suffers Defense Down.' },
    ultimate: { id: 'blood_moon', name: 'Blood Moon', type: 'damage', targetType: 'all_enemy', power: 1.35, desc: 'Damages every enemy and heals himself for a share of the total damage dealt - extra effect vs Bleeding targets.' },
  },
  {
    id: 'chronomancer', name: 'Chronomancer', role: 'Support', icon: '⏳', color: '#4fd1c5',
    difficulty: 'Master',
    base: { hp: 820, attack: 68, defense: 60, speed: 100, critRate: 8, critDmg: 150 },
    description: 'A time-weaver who manipulates the turn order itself rather than dealing damage.',
    strengths: ['Unique turn-order manipulation', 'Can undo recent damage on an ally', 'Great strategic utility'],
    weaknesses: ['Very low damage', 'Fragile', 'High-complexity kit', 'Vulnerable to burst and Silence'],
    passive: { name: 'Time Flow', desc: 'While in the Middle or Back Row, her turn-manipulation skills are slightly more effective.' },
    basicAttack: { id: 'time_bolt', name: 'Time Bolt', type: 'damage', targetType: 'single_enemy', power: 0.75, energyGain: 12 },
    skill1: { id: 'rewind', name: 'Rewind', type: 'special', targetType: 'single_ally', power: 0, cooldown: 4, energyGain: 15, desc: "Restores an ally's HP to an earlier snapshot, restores some Energy, and cleanses a debuff. Cannot revive the fallen." },
    skill2: { id: 'time_shift', name: 'Time Shift', type: 'special', targetType: 'single_ally', power: 0, cooldown: 3, energyGain: 15, desc: 'Advances an ally\'s action gauge, bringing their next turn closer (never grants an instant extra turn).' },
    ultimate: { id: 'freezing_time', name: 'Freezing Time', type: 'debuff', targetType: 'all_enemy', power: 0,
      desc: 'Freezes every enemy in place for the next 2 individual turns to occur (allies\' turns count too), preventing them from acting.' },
  },
  {
    id: 'illusionist', name: 'Illusionist', role: 'Mage', icon: '🎭', color: '#9b59b6',
    difficulty: 'Master',
    base: { hp: 830, attack: 122, defense: 62, speed: 99, critRate: 12, critDmg: 160 },
    description: 'A trickster who wins fights by making sure the enemy can never be quite sure what they are looking at.',
    strengths: ['Personal evasion', 'Can fully block incoming hits with a Decoy', 'Disrupts enemy targeting'],
    weaknesses: ['Low direct damage', 'Weak to AoE (which ignores single-target evasion tricks)', 'Weak to true/unavoidable damage'],
    passive: { name: 'Mirror Image', desc: 'A modest chance to fully evade an incoming attack (an illusion takes the hit instead).' },
    basicAttack: { id: 'arcane_mirror', name: 'Arcane Mirror', type: 'damage', targetType: 'single_enemy', power: 0.85, energyGain: 10 },
    skill1: { id: 'decoy', name: 'Decoy', type: 'buff', targetType: 'self', power: 0, cooldown: 4, energyGain: 10,
      statuses: [{ id: 'decoy_ward', duration: 3, chance: 100 }], desc: 'Conjures a decoy that fully blocks the next 2 hits, then grants Energy when it breaks.' },
    skill2: { id: 'confusion_cast', name: 'Confusion', type: 'debuff', targetType: 'single_enemy', power: 0.5, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'confusion', duration: 2, chance: 75 }], desc: 'The target may occasionally mis-target their next actions.' },
    ultimate: { id: 'grand_illusion', name: 'Grand Illusion', type: 'buff', targetType: 'all_ally', power: 0,
      statuses: [{ id: 'illusion_veil', duration: 2, chance: 100 }], desc: 'Wreathes the whole team in illusions, granting a temporary evasion window.' },
  },
  {
    id: 'alchemist', name: 'Alchemist', role: 'Support', icon: '⚗️', color: '#2ea55a',
    difficulty: 'Hard',
    base: { hp: 900, attack: 108, defense: 70, speed: 90, critRate: 10, critDmg: 155 },
    description: 'A field chemist who carries a rack of up to 10 volatile bottles into battle, spending them on powerful effects.',
    strengths: ['Very flexible toolkit', 'Strong AoE and cleanse options', 'Full resource refill on demand'],
    weaknesses: ['Every skill costs bottles - runs dry without managing them', 'Low direct sustained damage', 'Vulnerable once out of bottles'],
    passive: { name: 'Volatile Mixtures', desc: 'Deals 15% bonus damage while holding 7 or more bottles.' },
    basicAttack: { id: 'alchemy_bolt', name: 'Alchemy Bolt', type: 'damage', targetType: 'single_enemy', power: 0.9, energyGain: 10, desc: 'Consumes 1 bottle for full power (reduced power if empty-handed).' },
    skill1: { id: 'healing_potion', name: 'Healing Potion', type: 'heal', targetType: 'single_ally', power: 1.35, energyGain: 15, desc: 'Consumes 3 bottles: restores HP and removes Poison from an ally. No cooldown - gated purely by bottles on hand.' },
    skill2: { id: 'explosive_strike', name: 'Explosive Strike', type: 'damage', targetType: 'adjacent_enemies', power: 0.75, energyGain: 15, desc: 'Consumes 3 bottles: hurls an explosive flask that damages a target and those beside them. No cooldown - gated purely by bottles on hand.' },
    ultimate: { id: 'compounding_chemicals', name: 'Compounding Chemicals', type: 'special', targetType: 'self', power: 0, desc: 'Brews a fresh batch, refilling her bottle rack up to 10.' },
  },
  {
    id: 'duelist', name: 'Duelist', role: 'Assassin', icon: '🤺', color: '#34495e',
    difficulty: 'Hard',
    base: { hp: 880, attack: 152, defense: 70, speed: 106, critRate: 20, critDmg: 175 },
    description: 'A single-target specialist who grows deadlier the longer she duels the same rival.',
    strengths: ['Excellent sustained single-target damage', 'Counter-attacks a marked rival', 'Punishes an isolated target hard'],
    weaknesses: ['Poor against multiple targets', 'Loses her stacks if forced to switch targets', 'Weak to crowd control chains'],
    passive: { name: 'Challenger', desc: 'Gains a stack (up to 3) each time she hits the same target consecutively, each stack adding bonus damage against them. Switching targets resets the stacks.' },
    basicAttack: { id: 'rapid_slash', name: 'Rapid Slash', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'challenge', name: 'Challenge', type: 'debuff', targetType: 'single_enemy', power: 0.7, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'duel_mark', duration: 3, chance: 100 }], desc: 'Marks a rival, locking in bonus damage against them.' },
    skill2: { id: 'riposte', name: 'Riposte', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'counter_stance', duration: 2, chance: 100 }], desc: 'If her Marked rival attacks her while this is active, she counters.' },
    ultimate: { id: 'final_duel', name: 'Final Duel', type: 'damage', targetType: 'single_enemy', power: 1.9,
      statuses: [{ id: 'duel_mark', duration: 3, chance: 100 }], desc: 'Challenges a rival to a duel: heavy damage, and both combatants hit harder against each other for a few turns.' },
  },
  {
    id: 'pirate_captain', name: 'Pirate Captain', role: 'Ranged', icon: '🏴‍☠️', color: '#8b5e3c',
    difficulty: 'Normal',
    base: { hp: 960, attack: 138, defense: 76, speed: 98, critRate: 16, critDmg: 165 },
    description: 'A cannon-wielding raider who marks targets for elimination and rearranges the battlefield with brute force.',
    strengths: ['Strong AoE', 'Can physically reposition enemies', 'Bonus damage vs Marked targets'],
    weaknesses: ['Needs a turn of setup for full value', 'Moderate single-target damage without a Mark'],
    passive: { name: 'Wanted', desc: 'Deals bonus damage against any target carrying his Wanted Mark.' },
    basicAttack: { id: 'pistol_shot_pirate', name: 'Pistol Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'marked_shot', name: 'Marked Shot', type: 'debuff', targetType: 'any_enemy', power: 0.5, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'wanted_mark', duration: 3, chance: 100 }], desc: 'Slaps a Wanted Mark on any enemy, prioritizing the Back Row.' },
    skill2: { id: 'explosive_barrel', name: 'Explosive Barrel', type: 'damage', targetType: 'front_row', power: 0.85, cooldown: 3, energyGain: 15, desc: 'Blasts the enemy Front Row and knocks survivors back a row (Front -> Middle).' },
    ultimate: { id: 'broadside', name: 'Broadside', type: 'damage', targetType: 'all_enemy', power: 1.4, desc: 'A full cannon salvo on the enemy formation, with bonus damage against the Wanted target.' },
  },
  {
    id: 'spirit_shaman', name: 'Spirit Shaman', role: 'Support', icon: '🪶', color: '#5dade2',
    difficulty: 'Master',
    base: { hp: 940, attack: 98, defense: 75, speed: 92, critRate: 8, critDmg: 150 },
    description: 'A totem-caller whose team-wide auras shift depending on which spirit she has bonded with.',
    strengths: ['Strong team utility', 'Flexible totem strategy', 'Solid team-wide Ultimate'],
    weaknesses: ['Low direct damage', 'Only one Totem can be active at a time', 'Requires setup to get full value'],
    passive: { name: 'Spirit Bond', desc: 'Only one Totem aura can be active for the team at a time - casting a new Totem replaces the old one.' },
    basicAttack: { id: 'spirit_bolt', name: 'Spirit Bolt', type: 'damage', targetType: 'single_enemy', power: 0.85, energyGain: 10 },
    skill1: { id: 'healing_totem', name: 'Healing Totem', type: 'special', targetType: 'all_ally', power: 0, cooldown: 3, energyGain: 15, desc: 'Plants a Healing Totem granting the whole team Regeneration for a few turns - can be active alongside the Spirit Totem.' },
    skill2: { id: 'spirit_totem', name: 'Spirit Totem', type: 'special', targetType: 'all_ally', power: 0, cooldown: 3, energyGain: 15, desc: 'Plants a Spirit Totem granting the whole team a Speed boost for a few turns - can be active alongside the Healing Totem.' },
    ultimate: { id: 'ancestral_spirits', name: 'Ancestral Spirits', type: 'buff', targetType: 'all_ally', power: 0,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }, { id: 'defense_up', duration: 2, chance: 100 }, { id: 'regeneration', duration: 2, chance: 100 }], desc: 'Calls on the ancestors to empower the whole team at once.' },
  },
  {
    id: 'gravity_mage', name: 'Gravity Mage', role: 'Mage', icon: '🕳️', color: '#4b3f72',
    difficulty: 'Master',
    base: { hp: 820, attack: 138, defense: 60, speed: 90, critRate: 12, critDmg: 160 },
    description: 'A formation-breaker who bends gravity to drag enemies out of position.',
    strengths: ['Powerful position manipulation', 'Strong against rigid formations', 'Good AoE control'],
    weaknesses: ['Low single-target burst', 'Fragile', 'Weak against high-Speed assassins who can reach her first'],
    passive: { name: 'Gravity Field', desc: 'Her hits leave enemies slightly heavier - a small Speed penalty that lingers briefly.' },
    basicAttack: { id: 'gravity_bolt', name: 'Gravity Bolt', type: 'damage', targetType: 'single_enemy', power: 0.85, energyGain: 10,
      statuses: [{ id: 'gravity_weight', duration: 1, chance: 55 }] },
    skill1: { id: 'gravity_pull', name: 'Gravity Pull', type: 'debuff', targetType: 'any_enemy', power: 0.9, cooldown: 3, energyGain: 15, desc: 'Damages any target and hauls them one row forward (no movement if already in Front).' },
    skill2: { id: 'gravity_push', name: 'Gravity Push', type: 'debuff', targetType: 'any_enemy', power: 0.9, cooldown: 3, energyGain: 15, desc: 'Damages any target and shoves them one row back (no movement if already in Back).' },
    ultimate: { id: 'singularity', name: 'Singularity', type: 'damage', targetType: 'all_enemy', power: 0.85,
      statuses: [{ id: 'slow', duration: 2, chance: 80 }], desc: 'Rips open a singularity that damages and slows the entire enemy team, dragging all of them together toward the Middle Row.' },
  },

  // ===================== ROSTER EXPANSION 2: 31-40 =====================

  {
    id: 'monk', name: 'Monk', role: 'Fighter', icon: '🥋', color: '#d9a441',
    difficulty: 'Hard',
    base: { hp: 980, attack: 148, defense: 82, speed: 104, critRate: 16, critDmg: 165 },
    description: 'A martial artist who builds Ki with every strike and unleashes it in devastating combos.',
    strengths: ['Strong sustained single-target damage', 'Scales with successful actions', 'Can trade damage for survival via Meditation'],
    weaknesses: ['Requires setup to reach full power', 'Vulnerable to crowd control interrupting his rhythm', 'Weak if unable to act'],
    passive: { name: 'Inner Ki', desc: 'Gains Ki (max 100) from landing Basic Attacks, Skills, or counters. High Ki grants a small Basic Attack damage bonus.' },
    basicAttack: { id: 'palm_strike', name: 'Palm Strike', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'palm_burst', name: 'Palm Burst', type: 'damage', targetType: 'single_enemy', power: 1.65, cooldown: 2, energyGain: 15, desc: 'A heavy strike that consumes 15 Ki for full power (works at reduced power without it).' },
    skill2: { id: 'meditation', name: 'Meditation', type: 'heal', targetType: 'self', power: 0.9, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'defense_up', duration: 1, chance: 100 }], desc: 'Recovers HP and Ki instead of attacking, briefly raising Defense.' },
    ultimate: { id: 'sevenfold_strike', name: 'Sevenfold Strike', type: 'damage', targetType: 'single_enemy', power: 1.6, desc: 'A flurry of strikes whose total damage scales with current Ki - resets most of his Ki afterward.' },
  },
  {
    id: 'demon_hunter', name: 'Demon Hunter', role: 'Ranged', icon: '🏹', color: '#7a2e2e',
    difficulty: 'Hard',
    base: { hp: 850, attack: 155, defense: 65, speed: 108, critRate: 20, critDmg: 170 },
    description: 'A relentless huntress who marks her prey and finishes what she starts.',
    strengths: ['Strong Back Row pressure', 'Execute damage against low-HP targets', 'Reliable single-target burst'],
    weaknesses: ['Weak against high-Defense Tanks', 'Low sustain', 'Vulnerable once caught out of position'],
    passive: { name: "Hunter's Mark", desc: 'Marked enemies take bonus damage from her. The Mark has a duration and does not stack indefinitely.' },
    basicAttack: { id: 'hunter_shot', name: 'Hunter Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'mark_of_death', name: 'Mark of Death', type: 'debuff', targetType: 'any_enemy', power: 0.5, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'hunter_mark', duration: 3, chance: 100 }], desc: "Applies Hunter's Mark - slightly stronger if the target is in the Back Row." },
    skill2: { id: 'piercing_shot', name: 'Piercing Shot', type: 'damage', targetType: 'single_back', power: 1.3, cooldown: 3, energyGain: 15, desc: 'A shot that flies past the Front Row to strike the Back Row directly; bonus damage vs Marked targets.' },
    ultimate: { id: 'execution', name: 'Execution', type: 'damage', targetType: 'single_enemy', power: 2.2, desc: 'A finishing blow with sharply increased damage against targets at or below 30% HP.' },
  },
  {
    id: 'engineer', name: 'Engineer', role: 'Ranged', icon: '⚙️', color: '#8a8f38',
    difficulty: 'Master',
    base: { hp: 900, attack: 100, defense: 72, speed: 88, critRate: 8, critDmg: 150 },
    description: 'A field technician who deploys a real, independently-targetable Turret to control the battlefield - enemies can shoot it down directly, but never touch Engineer through it.',
    strengths: ['Sustained chip damage from the Turret', 'Battlefield control', 'Can repair the Turret mid-fight'],
    weaknesses: ['Setup time before the Turret pays off', 'The Turret can be killed like any other unit', 'Weak if rushed before deploying'],
    passive: { name: 'Auto Shoot', desc: "At the start of Engineer's turn, her Turret fires at 1 random enemy in the Front Row (Middle, then Back, if empty) - once upgraded into a War Machine, it instead fires at every enemy in that row." },
    basicAttack: { id: 'tech_shot', name: 'Tech Shot', type: 'damage', targetType: 'single_enemy', power: 0.85, energyGain: 10 },
    skill1: { id: 'deploy_turret_eng', name: 'Deploy Turret', type: 'special', targetType: 'self', power: 0, cooldown: 4, energyGain: 15, desc: 'Deploys a Turret as a real unit on the battlefield - enemies can target and destroy it directly, but Engineer herself is never hit through it. Only one Turret at a time.' },
    skill2: { id: 'repair', name: 'Repair', type: 'special', targetType: 'self', power: 0, cooldown: 3, energyGain: 15, desc: "Restores 50% of the Turret's (or War Machine's) max HP." },
    ultimate: { id: 'war_machine', name: 'War Machine', type: 'special', targetType: 'self', power: 0, desc: 'Upgrades the Turret into a War Machine (permanently bigger HP and Attack) and fires immediately. For the next 2 of her turns, it fires at the whole row instead of one random enemy.' },
  },
  {
    id: 'fencer', name: 'Fencer', role: 'Fighter', icon: '🤺', color: '#5c7a99',
    difficulty: 'Hard',
    base: { hp: 850, attack: 145, defense: 66, speed: 118, critRate: 18, critDmg: 170 },
    description: 'A nimble duelist who lives and dies by footwork, weaving between attacks.',
    strengths: ['High mobility and evasion', 'Strong single-target pressure', 'Good against slow, predictable attackers'],
    weaknesses: ['Low HP', 'Weak to AoE and true damage that ignore evasion', 'Weak to hard crowd control'],
    passive: { name: 'Footwork', desc: 'Gains a stacking Footwork buff (up to 3) from attacking, repositioning, or dodging - each stack adds Evasion.' },
    basicAttack: { id: 'rapid_thrust', name: 'Rapid Thrust', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'lunge', name: 'Lunge', type: 'damage', targetType: 'single_enemy', power: 1.3, cooldown: 2, energyGain: 15, desc: 'Strikes a target and advances a row forward if possible.' },
    skill2: { id: 'riposte_fencer', name: 'Riposte', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'parry_stance', duration: 1, chance: 100 } ], desc: 'A defensive stance: dodge or counter the next attack against her.' },
    ultimate: { id: 'thousand_thrusts', name: 'Thousand Thrusts', type: 'damage', targetType: 'single_enemy', power: 0.75, desc: 'A rapid multi-hit flurry - more hits land the more Footwork stacks she has built. Resets Footwork afterward.' },
  },
  {
    id: 'oracle', name: 'Oracle', role: 'Support', icon: '🔮', color: '#8e6fb0',
    difficulty: 'Master',
    base: { hp: 800, attack: 62, defense: 58, speed: 95, critRate: 6, critDmg: 150 },
    description: 'A seer who bends fate itself, protecting allies from misfortune before it happens.',
    strengths: ['Strong defensive prediction', 'Can neutralize a single enemy strike', 'Can prevent one lethal hit'],
    weaknesses: ['Very low damage', 'Fragile', 'Requires good timing to get full value'],
    passive: { name: 'Premonition', desc: "Reveals a light hint about a target's danger level (e.g. High Threat, Ultimate Ready) without exposing the AI's full plan." },
    basicAttack: { id: 'fate_bolt', name: 'Fate Bolt', type: 'damage', targetType: 'single_enemy', power: 0.7, energyGain: 12 },
    skill1: { id: 'prophecy', name: 'Prophecy', type: 'buff', targetType: 'all_ally', power: 0, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'evasion_up', duration: 1, chance: 100 }], desc: 'Grants the whole team a large Evasion boost for 1 turn.' },
    skill2: { id: 'fate_seal', name: 'Fate Seal', type: 'debuff', targetType: 'all_enemy', power: 0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'evasion_down', duration: 1, chance: 100 }], desc: "Cuts every enemy's Evasion for 1 turn." },
    ultimate: { id: 'alter_fate', name: 'Alter Fate', type: 'buff', targetType: 'all_ally', power: 0,
      statuses: [{ id: 'crit_up_team', duration: 3, chance: 100 }], desc: 'Bends fate in the whole team\'s favor, sharply raising Critical Chance for several turns.' },
  },
  {
    id: 'bard', name: 'Bard', role: 'Support', icon: '🎵', color: '#c98fb0',
    difficulty: 'Hard',
    base: { hp: 860, attack: 90, defense: 65, speed: 93, critRate: 8, critDmg: 150 },
    description: 'A performer who shifts the tide of battle by switching between musical stances.',
    strengths: ['Flexible team-wide utility', 'Adapts to the situation via stance', 'Strong when the team can capitalize on the buff'],
    weaknesses: ['Low personal damage', 'Needs the right stance active to matter', 'Weak in isolation'],
    passive: { name: 'Musical Rhythm', desc: 'Builds a stacking Rhythm buff (up to 3) from acting, strengthening her support effects.' },
    basicAttack: { id: 'sonic_note', name: 'Sonic Note', type: 'damage', targetType: 'single_enemy', power: 0.8, energyGain: 10 },
    skill1: { id: 'battle_song', name: 'Battle Song', type: 'special', targetType: 'all_ally', power: 0, cooldown: 3, energyGain: 15, desc: 'Switches to Battle Song stance, granting the team Attack Up.' },
    skill2: { id: 'war_drum', name: 'War Drum', type: 'special', targetType: 'all_ally', power: 0, cooldown: 4, energyGain: 15, desc: 'Switches to War Drum stance, granting the team Speed Up, HP Regeneration, and a touch of Energy.' },
    ultimate: { id: 'grand_performance', name: 'Grand Performance', type: 'special', targetType: 'all_ally', power: 0, desc: "A big finish whose effect depends on her active stance: Battle Song empowers the team's Attack, War Drum empowers Speed/Energy, and with no stance active she instead plays a Lullaby that weakens every enemy's Attack." },
  },
  {
    id: 'gladiator', name: 'Gladiator', role: 'Tank', icon: '⚔️', color: '#b5652b',
    difficulty: 'Normal',
    base: { hp: 1220, attack: 135, defense: 105, speed: 85, critRate: 12, critDmg: 160 },
    description: 'A crowd-pleasing brawler who feeds on Rage and forces enemies to face him.',
    strengths: ['Strong frontline sustain', 'Scales with the fight via Rage', 'Can force enemies to attack him with Taunt'],
    weaknesses: ['Weak to crowd control', 'Weak if enemies can ignore his Taunt', 'Loses value if kited'],
    passive: { name: 'Crowd Favorite', desc: 'Gains Rage (max 100) from dealing damage, taking damage, or surviving a critical hit.' },
    basicAttack: { id: 'arena_strike', name: 'Arena Strike', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'brutal_swing', name: 'Brutal Swing', type: 'damage', targetType: 'front_row', power: 0.85, cooldown: 2, energyGain: 15, desc: 'A sweeping blow across the enemy Front Row that builds extra Rage.' },
    skill2: { id: 'taunting_roar', name: 'Taunting Roar', type: 'debuff', targetType: 'front_row', power: 0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'taunt', duration: 2, chance: 100 }], desc: 'Taunts the enemy Front Row, drawing their attacks toward him for a couple of turns.' },
    ultimate: { id: 'arena_champion', name: 'Arena Champion', type: 'buff', targetType: 'self', power: 0,
      statuses: [{ id: 'attack_up', duration: 3, chance: 100 }, { id: 'defense_up', duration: 3, chance: 100 }, { id: 'rage_shield', duration: 3, chance: 100 }], desc: 'Consumes Rage to empower himself with Attack, Defense, and damage reduction - stronger the more Rage he had.' },
  },
  {
    id: 'frost_knight', name: 'Frost Knight', role: 'Tank', icon: '❄️', color: '#7fb3c9',
    difficulty: 'Hard',
    base: { hp: 1280, attack: 98, defense: 126, speed: 70, critRate: 6, critDmg: 150 },
    description: 'An armored sentinel who turns punishment into protection and freezes anyone who gets close.',
    strengths: ['Very tanky frontline', 'Strong crowd control (Slow/Freeze)', 'Gets tougher the longer he tanks hits'],
    weaknesses: ['Low Speed', 'Vulnerable to Burn/Fire-flavored counters', 'Vulnerable to control himself'],
    passive: { name: 'Ice Armor', desc: 'Gains a stacking Ice Stack (max 5) whenever he takes damage, each adding a small Defense bonus; at max stacks his Frost skills gain bonus effect.' },
    basicAttack: { id: 'frozen_blade', name: 'Frozen Blade', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10,
      statuses: [{ id: 'slow', duration: 1, chance: 40 }] },
    skill1: { id: 'ice_wall_fk', name: 'Ice Wall', type: 'shield', targetType: 'self', power: 0.6, cooldown: 3, energyGain: 15, desc: 'Raises a shield of ice; whoever fully breaks it is Slowed.' },
    skill2: { id: 'frost_bind', name: 'Frost Bind', type: 'debuff', targetType: 'single_enemy', power: 0.9, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'slow', duration: 2, chance: 85 }], desc: 'Damages and Slows a target - if they are already Slowed, briefly Freezes them instead.' },
    ultimate: { id: 'absolute_zero_fk', name: 'Absolute Zero', type: 'damage', targetType: 'all_enemy', power: 1.1,
      statuses: [{ id: 'slow', duration: 2, chance: 75 }], desc: 'An area attack that Slows the whole enemy team - stronger against already-Slowed targets.' },
  },
  {
    id: 'plague_doctor', name: 'Plague Doctor', role: 'Assassin', icon: '☠️', color: '#4a5c3a',
    difficulty: 'Master',
    base: { hp: 870, attack: 118, defense: 66, speed: 90, critRate: 10, critDmg: 155 },
    description: 'A disease-flinging disruptor who thrives as fights drag on and healing runs thin.',
    strengths: ['Strong in long battles', 'Anti-heal pressure', 'Can spread debuffs across the enemy team'],
    weaknesses: ['Low burst damage', 'Weak against Cleanse-heavy teams', 'Weak in short, fast fights'],
    passive: { name: 'Contagion', desc: 'His debuffs have a chance to spread to another enemy, up to a limited number of targets with an internal cooldown to prevent runaway chains.' },
    basicAttack: { id: 'infected_strike', name: 'Infected Strike', type: 'damage', targetType: 'single_enemy', power: 0.9, energyGain: 10,
      statuses: [{ id: 'disease', duration: 2, chance: 30 }] },
    skill1: { id: 'poison_flask', name: 'Poison Flask', type: 'damage', targetType: 'single_enemy', power: 0.7, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'poison', duration: 3, chance: 90 }], desc: 'Coats a target in poison for heavy damage over time.' },
    skill2: { id: 'pandemic', name: 'Pandemic', type: 'debuff', targetType: 'single_enemy', power: 0, cooldown: 3, energyGain: 15, desc: "Extends the target's Poison/Disease and attempts to spread it to up to 2 nearby enemies." },
    ultimate: { id: 'black_plague', name: 'Black Plague', type: 'debuff', targetType: 'single_enemy', power: 0.5,
      statuses: [{ id: 'disease', duration: 3, chance: 100 }, { id: 'healing_reduction', duration: 3, chance: 100 }, { id: 'attack_down', duration: 3, chance: 100 }], desc: 'Afflicts a target with a devastating combination of Disease, Healing Reduction, and Attack Down.' },
  },
  {
    id: 'void_walker', name: 'Void Walker', role: 'Assassin', icon: '🕳️', color: '#2e1a47',
    difficulty: 'Master',
    base: { hp: 800, attack: 158, defense: 58, speed: 110, critRate: 18, critDmg: 175 },
    description: 'A void-touched blade who blinks across the battlefield to strike where it hurts most.',
    strengths: ['Strong Back Row pressure', 'High mobility', 'Explosive burst damage'],
    weaknesses: ['Low HP', 'Vulnerable to crowd control and roots', 'Weak if caught without an escape'],
    passive: { name: 'Void Step', desc: 'After teleporting (Blink, Void Strike, or Void Collapse), briefly gains a ward that blocks the next incoming attack entirely.' },
    basicAttack: { id: 'void_blade', name: 'Void Blade', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'blink', name: 'Blink', type: 'special', targetType: 'self', power: 0, cooldown: 3, energyGain: 10, desc: 'Teleports to any open slot on the battlefield, gaining a post-teleport ward and a burst of Speed.' },
    skill2: { id: 'void_strike', name: 'Void Strike', type: 'damage', targetType: 'single_back', power: 1.18, cooldown: 2, energyGain: 15, desc: 'Blinks directly to a Back Row target and strikes with high damage, gaining a post-teleport ward.' },
    ultimate: { id: 'void_collapse', name: 'Void Collapse', type: 'damage', targetType: 'adjacent_enemies', power: 0.95, desc: 'Blinks into the heart of the enemy formation for an area of void damage before returning, gaining a post-teleport ward.' },
  },

  // ===================== ROSTER EXPANSION 3: 41-50 =====================

  {
    id: 'dragon_knight', name: 'Dragon Knight', role: 'Tank', icon: '🐲', color: '#c0392b',
    difficulty: 'Master',
    base: { hp: 1150, attack: 145, defense: 110, speed: 88, critRate: 14, critDmg: 165 },
    description: 'A draconic warrior who channels rising battle-fury into a devastating transformation.',
    strengths: ['Very durable frontline', 'Powerful transformation burst', 'High sustained damage once online'],
    weaknesses: ['Weak before transformation', 'Slow', 'Vulnerable to crowd control', 'Requires setup'],
    passive: { name: 'Dragon Blood', desc: 'Builds a Dragon Gauge (max 100) from dealing damage, taking damage, or using defensive skills.' },
    rowSynergy: { row: 'front', stat: 'defense', percent: 10, desc: '+10% Defense while positioned in the Front Row (his Guard is also stronger here).' },
    basicAttack: { id: 'dragon_slash', name: 'Dragon Slash', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10,
      statuses: [{ id: 'burn', duration: 2, chance: 25 }] },
    skill1: { id: 'dragon_guard', name: 'Dragon Guard', type: 'shield', targetType: 'self', power: 0.55, cooldown: 3, energyGain: 15, desc: 'Gains a shield and damage reduction while building Dragon Gauge - stronger in the Front Row.' },
    skill2: { id: 'dragon_breath', name: 'Dragon Breath', type: 'damage', targetType: 'front_row', power: 0.8, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'burn', duration: 2, chance: 70 }], desc: 'Breathes fire across the enemy Front Row - hits harder with a high Dragon Gauge.' },
    ultimate: { id: 'dragon_form', name: 'Dragon Form', type: 'buff', targetType: 'self', power: 0,
      statuses: [{ id: 'dragon_form', duration: 4, chance: 100 }], desc: 'If his Dragon Gauge is high enough, transforms for several turns of greatly increased Attack and Defense (consumes the Gauge to prevent back-to-back transformations).' },
  },
  {
    id: 'shadow_priest', name: 'Shadow Priest', role: 'Support', icon: '🖤', color: '#4a3a5a',
    difficulty: 'Master',
    base: { hp: 780, attack: 68, defense: 58, speed: 92, critRate: 6, critDmg: 150 },
    description: 'A support who channels her own life force into powerful, high-risk team blessings.',
    strengths: ['Very strong team-wide buffs', 'Healing that scales when she is in danger', 'High reward for careful HP management'],
    weaknesses: ['Low personal survivability', 'Vulnerable to burst and target isolation', 'Weak to anti-heal'],
    passive: { name: 'Dark Blessing', desc: 'Gains a modest healing/effect bonus while her own HP is below 40%.' },
    basicAttack: { id: 'shadow_bolt', name: 'Shadow Bolt', type: 'damage', targetType: 'single_enemy', power: 0.85, energyGain: 12 },
    skill1: { id: 'shadow_heal', name: 'Shadow Heal', type: 'special', targetType: 'single_ally', power: 0, cooldown: 2, energyGain: 15,
      desc: "You choose how much of her own HP to sacrifice - the ally receives 2x that amount as healing. Can't target herself; her HP can never drop below 1." },
    skill2: { id: 'life_taker', name: 'Life Taker', type: 'special', targetType: 'single_enemy', power: 0, cooldown: 3, energyGain: 15,
      desc: "Siphons a percentage of an enemy's HP as healing for herself, without actually reducing the enemy's HP." },
    ultimate: { id: 'soul_sacrifice', name: 'Soul Sacrifice', type: 'special', targetType: 'single_enemy', power: 0, cooldown: 2,
      desc: "You choose how much of her own HP to sacrifice - the enemy loses that same amount of HP (1:1). Her HP can never drop below 1." },
  },
  {
    id: 'sniper', name: 'Sniper', role: 'Ranged', icon: '🎯', color: '#3a5a3a',
    difficulty: 'Hard',
    base: { hp: 820, attack: 152, defense: 60, speed: 100, critRate: 24, critDmg: 180 },
    description: 'A patient marksman who lines up the perfect shot and lets precision do the rest.',
    strengths: ['Excellent long-range single-target damage', 'Strong backline pressure', 'Very high Critical stats'],
    weaknesses: ['Fragile', 'Vulnerable while lining up Aim', 'Low mobility'],
    passive: { name: 'Long Range', desc: 'Deals modestly more damage the further her target is from her - strongest when both she and the target are in the Back Row.' },
    basicAttack: { id: 'precision_shot', name: 'Precision Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'aim', name: 'Aim', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'aim_stance', duration: 1, chance: 100 }], desc: "Steadies her Aim - her next shot completely ignores the target's Evasion, Defense, and Shield." },
    skill2: { id: 'piercing_bullet', name: 'Piercing Bullet', type: 'damage', targetType: 'single_back', power: 1.35, cooldown: 3, energyGain: 15, desc: 'A shot that punches straight through the Front Row to hit the Back Row.' },
    ultimate: { id: 'headshot', name: 'Headshot', type: 'damage', targetType: 'any_enemy', power: 2.1, desc: 'An extremely precise, high-critical shot on any target - bonus damage against low-HP enemies.' },
  },
  {
    id: 'berserker_lord', name: 'Berserker Lord', role: 'Fighter', icon: '🪓', color: '#8b2e2e',
    difficulty: 'Hard',
    base: { hp: 1080, attack: 150, defense: 90, speed: 96, critRate: 14, critDmg: 165 },
    description: 'A warlord who feeds on the chaos of battle, growing more dangerous the longer the Rage builds.',
    strengths: ['Scales hard with Rage', 'Strong burst once Rage is high', 'Punishing AoE'],
    weaknesses: ['Vulnerable to crowd control', 'Low Defense for a Fighter', 'Can be kited'],
    passive: { name: 'Enrage', desc: 'Builds Rage (max 100) from dealing damage, taking damage, or an ally falling.' },
    basicAttack: { id: 'savage_cleave', name: 'Savage Cleave', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10, desc: 'Damage scales up slightly with current Rage.' },
    skill1: { id: 'blood_roar', name: 'Blood Roar', type: 'damage', targetType: 'all_enemy', power: 0.55, cooldown: 3, energyGain: 10,
      desc: 'Sacrifices some HP for a large burst of Rage and an Attack boost, and roars a wave of damage across every enemy.' },
    skill2: { id: 'raging_swing', name: 'Raging Swing', type: 'damage', targetType: 'front_row', power: 0.8, cooldown: 3, energyGain: 15, desc: 'A wide swing across the enemy Front Row - hits much harder with high Rage.' },
    ultimate: { id: 'wrath_unleashed', name: 'Wrath Unleashed', type: 'damage', targetType: 'single_enemy', power: 1.8, desc: 'Consumes most of his Rage for a devastating blow - if Rage was very high, briefly shatters the target\'s Armor.' },
  },
  {
    id: 'rune_master', name: 'Rune Master', role: 'Mage', icon: '🔯', color: '#6b8fb0',
    difficulty: 'Master',
    base: { hp: 830, attack: 120, defense: 64, speed: 91, critRate: 10, critDmg: 155 },
    description: 'A methodical spellcaster who inscribes Runes and fuses them into powerful combined effects.',
    strengths: ['Extremely flexible toolkit', 'Rewards planning ahead', 'Strong payoff when Runes are fused'],
    weaknesses: ['Low immediate power', 'Complex - needs setup turns', 'Vulnerable to Silence/disruption'],
    passive: { name: 'Arcane Inscription', desc: 'Holds up to 3 Runes (Fire, Guard, Wind) at once, inscribed one at a time via Inscribe.' },
    basicAttack: { id: 'rune_bolt', name: 'Rune Bolt', type: 'damage', targetType: 'single_enemy', power: 0.9, energyGain: 10, desc: 'Empowered by her active Runes - Fire adds damage, Guard adds a sliver of Shield, Wind speeds her turn slightly.' },
    skill1: { id: 'inscribe', name: 'Inscribe', type: 'special', targetType: 'self', power: 0, cooldown: 1, energyGain: 12, desc: 'Inscribes the next Rune in her rotation (Fire -> Guard -> Wind), up to 3 held at once.' },
    skill2: { id: 'rune_fusion', name: 'Rune Fusion', type: 'damage', targetType: 'single_enemy', power: 1.1, cooldown: 2, energyGain: 15, desc: "Fuses two of her active Runes into a combat effect using predefined recipes (Fire+Fire=Burst, Fire+Wind=Rapid, Fire+Guard=Barrier, Wind+Wind=Haste, Guard+Guard=Fortress, Guard+Wind=Mobility)." },
    ultimate: { id: 'grand_rune', name: 'Grand Rune', type: 'damage', targetType: 'all_enemy', power: 1.25, desc: "A powerful effect determined by her current Rune combination - then clears her Runes." },
  },
  {
    id: 'witch', name: 'Witch', role: 'Mage', icon: '🧙‍♀️', color: '#5a3a6b',
    difficulty: 'Master',
    base: { hp: 810, attack: 122, defense: 60, speed: 94, critRate: 10, critDmg: 155 },
    description: 'A hex-slinger whose curses compound the longer a fight drags on.',
    strengths: ['Strong sustained debuff pressure', 'Can steal or transfer debuffs', 'Excellent in long fights'],
    weaknesses: ['Low burst', 'Weak against Cleanse-heavy teams', 'Weak in short, fast fights'],
    passive: { name: 'Witchcraft', desc: "Her Hex effects grow stronger based on how many debuffs the target already carries (capped at 3 stacks of bonus)." },
    basicAttack: { id: 'hex_bolt', name: 'Hex Bolt', type: 'damage', targetType: 'single_enemy', power: 0.85, energyGain: 10,
      statuses: [{ id: 'attack_down', duration: 1, chance: 32 }] },
    skill1: { id: 'hex', name: 'Hex', type: 'debuff', targetType: 'single_enemy', power: 0.55, cooldown: 2, energyGain: 15, desc: 'Damages a target and curses them with a random debuff drawn fairly from Attack Down, Defense Down, Speed Down, Healing Reduction, or Poison.' },
    skill2: { id: 'curse_transfer', name: 'Curse Transfer', type: 'special', targetType: 'single_ally', power: 0, cooldown: 3, energyGain: 15, desc: "Lifts a debuff from an ally and hurls it onto a random enemy instead." },
    ultimate: { id: 'witchs_sabbath', name: "Witch's Sabbath", type: 'debuff', targetType: 'all_enemy', power: 0.95,
      statuses: [{ id: 'poison', duration: 3, chance: 95 }, { id: 'defense_down', duration: 3, chance: 90 }], desc: 'Damages the entire enemy team and curses them with lingering Hexes.' },
  },
  {
    id: 'battle_medic', name: 'Battle Medic', role: 'Support', icon: '⛑️', color: '#c94f4f',
    difficulty: 'Normal',
    base: { hp: 880, attack: 100, defense: 68, speed: 96, critRate: 10, critDmg: 155 },
    description: 'A frontline combat healer who keeps the team standing without giving up her own offense.',
    strengths: ['Flexible healing plus offensive utility', 'Bonus healing after attacking', 'Good emergency triage'],
    weaknesses: ['Lower raw healing than a dedicated healer', 'Fragile', 'Limited burst'],
    passive: { name: 'Emergency Protocol', desc: 'Heals for extra when treating an ally at critically low HP.' },
    basicAttack: { id: 'medical_shot', name: 'Medical Shot', type: 'damage', targetType: 'single_enemy', power: 0.8, energyGain: 10 },
    skill1: { id: 'combat_heal', name: 'Combat Heal', type: 'heal', targetType: 'single_ally', power: 1.12, cooldown: 2, energyGain: 15, desc: 'Heals an ally - stronger if she attacked on her previous turn.' },
    skill2: { id: 'adrenaline_shot', name: 'Adrenaline Shot', type: 'buff', targetType: 'single_ally', power: 0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'attack_up', duration: 3, chance: 100 }, { id: 'speed_up', duration: 3, chance: 100 }], desc: 'Injects an ally with Attack Up and Speed Up.' },
    ultimate: { id: 'mass_trauma_care', name: 'Mass Trauma Care', type: 'heal', targetType: 'all_ally', power: 1.0, desc: 'Heals the whole team - the more HP an ally is missing, the more they recover, up to a cap.' },
  },
  {
    id: 'beast_rider', name: 'Beast Rider', role: 'Fighter', icon: '🐺', color: '#a67c52',
    difficulty: 'Master',
    base: { hp: 950, attack: 140, defense: 78, speed: 116, critRate: 16, critDmg: 165 },
    description: 'A mounted skirmisher who trades her mount\'s speed for raw sturdiness when the fight calls for it.',
    strengths: ['Very high Speed while Mounted', 'Strong position control via Charge', 'Flexible Mounted/Dismounted trade-off'],
    weaknesses: ['Vulnerable to Root/Slow', 'Weaker offense once Dismounted', 'Needs good positioning'],
    passive: { name: 'Mounted Combat', desc: 'While Mounted, gains bonus Speed and a small Attack bonus.' },
    mountedBonus: { stat: 'speed', percent: 22 },
    basicAttack: { id: 'beast_strike', name: 'Beast Strike', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'charge', name: 'Charge', type: 'damage', targetType: 'single_enemy', power: 1.15, cooldown: 2, energyGain: 15, desc: 'Charges a target for damage and tramples them, causing a Stun.' },
    skill2: { id: 'dismount', name: 'Dismount', type: 'buff', targetType: 'self', power: 0, cooldown: 4, energyGain: 10,
      statuses: [{ id: 'defense_up', duration: 99, chance: 100 }, { id: 'speed_down', duration: 99, chance: 100 }], desc: 'Dismounts for the rest of the battle: trades Speed for a lasting Defense boost.' },
    ultimate: { id: 'beast_rampage', name: 'Beast Rampage', type: 'damage', targetType: 'front_row', power: 1.3, desc: 'She and her beast tear through the enemy Front Row together.' },
  },
  {
    id: 'mirror_knight', name: 'Mirror Knight', role: 'Tank', icon: '🪞', color: '#8fa6c9',
    difficulty: 'Master',
    base: { hp: 1240, attack: 92, defense: 122, speed: 74, critRate: 6, critDmg: 150 },
    description: 'An enchanted guardian who turns attackers\' own strength against them.',
    strengths: ['Punishes direct attackers', 'Very tanky', 'Strong against auto-attack-heavy teams'],
    weaknesses: ['DoT and indirect damage bypass his reflection', 'Weak to sustained debuffs', 'Low personal damage'],
    passive: { name: 'Mirror Armor', desc: 'Reflects a capped share of direct attack damage back at the attacker. Reflected damage can never itself trigger another reflection.' },
    reflectPercent: 20,
    basicAttack: { id: 'mirror_slash', name: 'Mirror Slash', type: 'damage', targetType: 'single_enemy', power: 0.9, energyGain: 10 },
    skill1: { id: 'mirror_shield', name: 'Mirror Shield', type: 'shield', targetType: 'self', power: 0.5, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'mirror_boost', duration: 2, chance: 100 }], desc: 'Gains a shield and a temporary boost to his reflect percentage.' },
    skill2: { id: 'reversal', name: 'Reversal', type: 'shield', targetType: 'self', power: 0.4, cooldown: 3, energyGain: 15, desc: 'Converts a portion of recent punishment into a shield.' },
    ultimate: { id: 'perfect_reflection', name: 'Perfect Reflection', type: 'buff', targetType: 'self', power: 0,
      statuses: [{ id: 'mirror_boost', duration: 3, chance: 100 }], desc: 'Sharply raises his reflect percentage for several turns, capped per hit so it can never spiral out of control.' },
  },
  {
    id: 'soul_reaper', name: 'Soul Reaper', role: 'Assassin', icon: '💀', color: '#2e2e3a',
    difficulty: 'Master',
    base: { hp: 830, attack: 150, defense: 62, speed: 104, critRate: 18, critDmg: 170 },
    description: 'A collector of souls who grows deadlier with every enemy that falls.',
    strengths: ['Massive snowball potential', 'Strong execute damage', 'Punishes weakened enemies hard'],
    weaknesses: ['Weak early before any kills', 'Vulnerable to Tanks that refuse to die', 'Needs protection to get going'],
    passive: { name: 'Soul Harvest', desc: 'Gains a Soul (max 5) whenever an enemy falls - each Soul boosts ALL of his damage by 25%.' },
    basicAttack: { id: 'soul_slash', name: 'Soul Slash', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10, desc: 'Damage scales up with current Soul count.' },
    skill1: { id: 'soul_mark', name: 'Soul Mark', type: 'debuff', targetType: 'single_enemy', power: 0.6, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'soul_mark_status', duration: 3, chance: 100 }], desc: 'Marks a target - if they die while Marked, he gains a bonus Soul.' },
    skill2: { id: 'reapers_cut', name: "Reaper's Cut", type: 'damage', targetType: 'single_enemy', power: 1.1, cooldown: 2, energyGain: 15, desc: "Bonus damage based on the target's missing HP." },
    ultimate: { id: 'reapers_domain', name: "Reaper's Domain", type: 'debuff', targetType: 'all_enemy', power: 0,
      statuses: [{ id: 'defense_down', duration: 2, chance: 60 }], desc: 'Opens a Soul Domain: he gains Attack Up, and weakened enemies suffer Defense Down.' },
  },
];

// Training Dummy: not part of the selectable roster (CHARACTERS array), used only
// by Practice and Character Test modes as a stationary, weak sparring partner.
const TRAINING_DUMMY = {
  id: 'training-dummy', name: 'Training Dummy', role: 'Specialist', icon: '🎯', color: '#666a70',
  difficulty: 'Easy',
  base: { hp: 2000, attack: 60, defense: 60, speed: 60, critRate: 5, critDmg: 150 },
  description: 'A stuffed practice target. Deals minimal damage and never uses skills strategically.',
  strengths: ['High HP - survives long test sessions'], weaknesses: ['Very low damage', 'No real strategy'],
  passive: { name: 'Inanimate', desc: 'No passive effect.' },
  basicAttack: { id: 'dummy_swing', name: 'Wobble', type: 'damage', targetType: 'single_enemy', power: 0.7, energyGain: 10 },
  skill1: { id: 'dummy_skill1', name: 'Creak', type: 'damage', targetType: 'single_enemy', power: 0.8, cooldown: 2, energyGain: 15, desc: 'A weak strike.' },
  skill2: { id: 'dummy_skill2', name: 'Wobble Harder', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10, statuses: [{ id: 'defense_up', duration: 2, chance: 100 }], desc: 'Braces itself.' },
  ultimate: { id: 'dummy_ultimate', name: 'Stuffing Burst', type: 'damage', targetType: 'single_enemy', power: 1.2, desc: 'Releases stuffing in a weak burst.' },
};

// Shared defend action (identical mechanics for every character, applied by combat engine)
const DEFEND_ACTION = {
  id: 'defend', name: 'Defend', type: 'defend',
  damageReduction: 40, energyGain: 8,
};

function getCharacterById(id) {
  return CHARACTERS.find(c => c.id === id) || null;
}
