/**
 * PONTI ARENA - Character Database
 * Centralized, data-driven character configuration.
 * Adding a new character = add one object here. No engine changes required.
 *
 * Skill effect vocabulary (consumed by combat.js / skills.js / targeting.js):
 *   type: 'damage' | 'heal' | 'buff' | 'debuff' | 'status' | 'shield' | 'special'
 *   targetType: 'single_enemy' (front-priority: nearest living row) | 'single_front' | 'single_middle' |
 *               'single_back' | 'any_enemy' (ignores row) | 'front_row' | 'middle_row' | 'back_row' |
 *               'all_enemy' | 'adjacent_enemies' (target + neighbors) |
 *               'single_ally' | 'all_ally' | 'self'
 *   power: multiplier applied to attacker.attack (for damage) or attacker.attack*0.x (for heal)
 *   statuses: [{ id, duration, chance }] status effects applied on hit
 *
 * rowSynergy: optional, purely-informational-plus-mechanical bonus this character gets while
 *   standing in a given formation row (see combat.js for where each is actually applied).
 * backlineBonus: optional flat % bonus damage this character deals when its target is in the Back Row,
 *   regardless of the attacker's own position (see combat.js).
 */

const CHARACTERS = [
  {
    id: 'knight', name: 'Knight', role: 'Tank', icon: '🛡️', color: '#8fa6c9',
    difficulty: 'Easy',
    base: { hp: 1350, attack: 95, defense: 130, speed: 70, critRate: 5, critDmg: 150 },
    description: 'A stalwart defender who shields allies at the cost of his own offense.',
    strengths: ['Very high HP', 'Very high Defense', 'Protects the team'],
    weaknesses: ['Low Speed', 'Low damage output'],
    passive: { name: 'Iron Will', desc: 'Gains +30% Defense whenever HP drops below 40%.' },
    rowSynergy: { row: 'front', stat: 'defense', percent: 20, desc: '+20% Defense while positioned in the Front Row.' },
    basicAttack: { id: 'sword_slash', name: 'Sword Slash', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'shield_bash', name: 'Shield Bash', type: 'damage', targetType: 'single_enemy', power: 1.2, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'stun', duration: 1, chance: 35 }], desc: 'Deals damage, chance to Stun.' },
    skill2: { id: 'guard', name: 'Guard', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'defense_up', duration: 2, chance: 100 }], desc: 'Sharply raises own Defense.' },
    ultimate: { id: 'royal_fortress', name: 'Royal Fortress', type: 'shield', targetType: 'all_ally', power: 0.6, desc: 'Shields the entire team.' },
  },
  {
    id: 'archer', name: 'Archer', role: 'Ranged', icon: '🏹', color: '#8fc98f',
    difficulty: 'Easy',
    base: { hp: 900, attack: 145, defense: 70, speed: 110, critRate: 20, critDmg: 165 },
    description: 'A precise marksman who punishes high-HP targets with crippling shots.',
    strengths: ['High Speed', 'Strong single-target damage'],
    weaknesses: ['Low HP', 'Low Defense'],
    passive: { name: 'Eagle Eye', desc: '+15% Critical Chance against targets above 50% HP.' },
    rowSynergy: { row: 'back', stat: 'critRate', percent: 15, desc: '+15% Critical Chance while positioned in the Back Row.' },
    basicAttack: { id: 'arrow_shot', name: 'Arrow Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'charged_arrow', name: 'Charged Arrow', type: 'damage', targetType: 'single_back', power: 1.6, cooldown: 2, energyGain: 15, desc: 'Piercing shot aimed at the enemy Back Row.' },
    skill2: { id: 'multi_shot', name: 'Multi Shot', type: 'damage', targetType: 'all_enemy', power: 0.75, cooldown: 3, energyGain: 15, desc: 'Fires at every enemy.' },
    ultimate: { id: 'rain_of_arrows', name: 'Rain of Arrows', type: 'damage', targetType: 'all_enemy', power: 1.4, desc: 'A devastating volley on all enemies.' },
  },
  {
    id: 'wizard', name: 'Wizard', role: 'Mage', icon: '🧙', color: '#b18fe0',
    difficulty: 'Normal',
    base: { hp: 850, attack: 155, defense: 65, speed: 90, critRate: 12, critDmg: 160 },
    description: 'A scholar of the arcane whose spells snowball in power the more he casts.',
    strengths: ['Very high burst', 'Scales with skill usage'],
    weaknesses: ['Low HP', 'Low Speed'],
    passive: { name: 'Arcane Mastery', desc: 'Each consecutive skill cast (not basic attack) grants +10% damage, stacking up to 3 times.' },
    basicAttack: { id: 'arcane_bolt', name: 'Arcane Bolt', type: 'damage', targetType: 'single_enemy', power: 0.9, energyGain: 10 },
    skill1: { id: 'fireball', name: 'Fireball', type: 'damage', targetType: 'single_enemy', power: 1.5, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'burn', duration: 2, chance: 60 }], desc: 'Deals damage and may Burn the target.' },
    skill2: { id: 'arcane_burst', name: 'Arcane Burst', type: 'damage', targetType: 'all_enemy', power: 0.9, cooldown: 3, energyGain: 15, desc: 'An explosion hitting all enemies.' },
    ultimate: { id: 'meteor', name: 'Meteor', type: 'damage', targetType: 'adjacent_enemies', power: 1.7, desc: 'Calls down a meteor on a target and its adjacent enemies.' },
  },
  {
    id: 'assassin', name: 'Assassin', role: 'Assassin', icon: '🗡️', color: '#c96b6b',
    difficulty: 'Hard',
    base: { hp: 780, attack: 165, defense: 55, speed: 118, critRate: 25, critDmg: 190 },
    description: 'A shadow-blade that finishes weakened targets in a single strike.',
    strengths: ['Extreme burst on low-HP targets', 'Very high Speed'],
    weaknesses: ['Very low HP', 'Very low Defense'],
    passive: { name: 'Killing Instinct', desc: '+35% damage against targets below 30% HP.' },
    backlineBonus: { percent: 30, desc: 'Shadow Hunter: +30% damage against enemies positioned in the Back Row.' },
    basicAttack: { id: 'dagger_strike', name: 'Dagger Strike', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'shadow_step', name: 'Shadow Step', type: 'damage', targetType: 'single_back', power: 1.3, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'defense_down', duration: 2, chance: 70 }], desc: 'Strikes and lowers target Defense.' },
    skill2: { id: 'poison_blade', name: 'Poison Blade', type: 'damage', targetType: 'single_enemy', power: 0.9, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'poison', duration: 3, chance: 90 }], desc: 'Poisons the target.' },
    ultimate: { id: 'death_mark', name: 'Death Mark', type: 'damage', targetType: 'single_enemy', power: 2.6, statuses: [{ id: 'mark', duration: 2, chance: 100 }], desc: 'A lethal finishing blow that Marks the target.' },
  },
  {
    id: 'berserker', name: 'Berserker', role: 'Fighter', icon: '🪓', color: '#d18a4a',
    difficulty: 'Normal',
    base: { hp: 1150, attack: 150, defense: 90, speed: 95, critRate: 15, critDmg: 170 },
    description: 'The lower his HP falls, the harder he hits.',
    strengths: ['Damage scales as HP drops', 'Durable bruiser'],
    weaknesses: ['Weak while at full HP', 'No mitigation'],
    passive: { name: 'Fury', desc: 'Gains up to +40% Attack as HP decreases (max at 20% HP).' },
    basicAttack: { id: 'heavy_axe', name: 'Heavy Axe', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'rage_strike', name: 'Rage Strike', type: 'damage', targetType: 'single_enemy', power: 1.4, cooldown: 2, energyGain: 20, desc: 'A furious blow that generates extra Energy.' },
    skill2: { id: 'blood_frenzy', name: 'Blood Frenzy', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }], desc: 'Raises own Attack.' },
    ultimate: { id: 'berserker_rage', name: 'Berserker Rage', type: 'damage', targetType: 'all_enemy', power: 1.3, desc: 'A wide cleave against all enemies.' },
  },
  {
    id: 'cleric', name: 'Cleric', role: 'Support', icon: '✨', color: '#e0d68f',
    difficulty: 'Easy',
    base: { hp: 950, attack: 75, defense: 80, speed: 88, critRate: 8, critDmg: 150 },
    description: 'A healer whose blessings keep the team standing.',
    strengths: ['High single-target healing', 'Cleanses debuffs'],
    weaknesses: ['Very low damage', 'Low Speed'],
    passive: { name: 'Holy Aura', desc: 'Allies regenerate 2% max HP at the start of their turn.' },
    rowSynergy: { row: 'back', stat: 'healPower', percent: 20, desc: '+20% Healing Done while positioned in the Back Row.' },
    basicAttack: { id: 'holy_strike', name: 'Holy Strike', type: 'damage', targetType: 'single_enemy', power: 0.8, energyGain: 10 },
    skill1: { id: 'heal', name: 'Heal', type: 'heal', targetType: 'single_ally', power: 1.6, cooldown: 1, energyGain: 15, desc: 'Restores HP to one ally.' },
    skill2: { id: 'purify', name: 'Purify', type: 'special', targetType: 'single_ally', power: 0, cooldown: 3, energyGain: 15, cleanse: true, desc: 'Removes all debuffs from an ally.' },
    ultimate: { id: 'divine_blessing', name: 'Divine Blessing', type: 'heal', targetType: 'all_ally', power: 1.1, desc: 'Heals the entire team.' },
  },
  {
    id: 'ranger', name: 'Ranger', role: 'Skirmisher', icon: '🎯', color: '#7fbf8f',
    difficulty: 'Normal',
    base: { hp: 980, attack: 135, defense: 78, speed: 105, critRate: 18, critDmg: 160 },
    description: 'A trapper who wears enemies down over time.',
    strengths: ['Damage-over-time pressure', 'Battlefield control'],
    weaknesses: ['Low upfront burst'],
    passive: { name: 'Hunter Instinct', desc: 'Basic Attacks against a Poisoned target deal +20% damage.' },
    basicAttack: { id: 'quick_shot', name: 'Quick Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'poison_arrow', name: 'Poison Arrow', type: 'damage', targetType: 'single_enemy', power: 1.1, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'poison', duration: 3, chance: 85 }], desc: 'Poisons the target.' },
    skill2: { id: 'trap', name: 'Trap', type: 'debuff', targetType: 'single_enemy', power: 0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'root', duration: 1, chance: 75 }, { id: 'speed_down', duration: 2, chance: 75 }], desc: 'Roots and slows the target.' },
    ultimate: { id: 'hunters_barrage', name: "Hunter's Barrage", type: 'damage', targetType: 'all_enemy', power: 1.2,
      statuses: [{ id: 'poison', duration: 3, chance: 60 }], desc: 'Strikes all enemies and may poison them.' },
  },
  {
    id: 'warlock', name: 'Warlock', role: 'Mage', icon: '💀', color: '#8a6bb0',
    difficulty: 'Hard',
    base: { hp: 870, attack: 150, defense: 62, speed: 92, critRate: 12, critDmg: 165 },
    description: 'A dark caster who trades allied life for enemy suffering.',
    strengths: ['Sustained drain damage', 'Curses reduce enemy output'],
    weaknesses: ['Fragile', 'No burst without setup'],
    passive: { name: 'Dark Pact', desc: 'Heals 15% of damage dealt by skills back to himself.' },
    basicAttack: { id: 'dark_bolt', name: 'Dark Bolt', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'curse', name: 'Curse', type: 'debuff', targetType: 'single_enemy', power: 0.6, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'attack_down', duration: 2, chance: 80 }], desc: 'Damages and weakens the target.' },
    skill2: { id: 'life_drain', name: 'Life Drain', type: 'damage', targetType: 'single_enemy', power: 1.2, cooldown: 2, energyGain: 15, drainPercent: 40, desc: 'Drains HP from the target to heal self.' },
    ultimate: { id: 'soul_harvest', name: 'Soul Harvest', type: 'damage', targetType: 'all_enemy', power: 1.5, drainPercent: 25, desc: 'Drains life from every enemy.' },
  },
  {
    id: 'ninja', name: 'Ninja', role: 'Assassin', icon: '🥷', color: '#556070',
    difficulty: 'Hard',
    base: { hp: 800, attack: 158, defense: 58, speed: 122, critRate: 22, critDmg: 175 },
    description: 'The fastest blade in the arena, gone before the counter lands.',
    strengths: ['Highest Speed in the roster', 'Evasive'],
    weaknesses: ['Low HP and Defense'],
    passive: { name: 'Evasion', desc: '15% chance to fully evade an incoming attack.' },
    evasionPercent: 15,
    basicAttack: { id: 'shuriken', name: 'Shuriken', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'shadow_dash', name: 'Shadow Dash', type: 'damage', targetType: 'single_back', power: 1.35, cooldown: 2, energyGain: 15, desc: 'A rapid strike targeting the enemy Back Row.' },
    skill2: { id: 'smoke_bomb', name: 'Smoke Bomb', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'speed_up', duration: 2, chance: 100 }], desc: 'Raises own Speed sharply.' },
    ultimate: { id: 'shadow_execution', name: 'Shadow Execution', type: 'damage', targetType: 'single_enemy', power: 2.7, desc: 'A precise, devastating finisher.' },
  },
  {
    id: 'frost-mage', name: 'Frost Mage', role: 'Control', icon: '❄️', color: '#8fd6e0',
    difficulty: 'Normal',
    base: { hp: 880, attack: 130, defense: 68, speed: 94, critRate: 10, critDmg: 155 },
    description: 'Locks enemies down with cold, buying the team room to breathe.',
    strengths: ['Strong crowd control', 'Team-wide slows'],
    weaknesses: ['Below-average raw damage'],
    passive: { name: 'Frozen Touch', desc: 'Skills have +15% chance to apply their status effects.' },
    basicAttack: { id: 'ice_bolt', name: 'Ice Bolt', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'frost_nova', name: 'Frost Nova', type: 'damage', targetType: 'front_row', power: 0.9, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'speed_down', duration: 2, chance: 65 }], desc: 'Chills and slows the entire enemy Front Row.' },
    skill2: { id: 'ice_wall', name: 'Ice Wall', type: 'shield', targetType: 'single_ally', power: 0.5, cooldown: 3, energyGain: 15, desc: 'Shields an ally with ice.' },
    ultimate: { id: 'absolute_zero', name: 'Absolute Zero', type: 'damage', targetType: 'all_enemy', power: 1.3,
      statuses: [{ id: 'freeze', duration: 1, chance: 55 }], desc: 'May Freeze the entire enemy team, skipping their next turn.' },
  },
  {
    id: 'pyromancer', name: 'Pyromancer', role: 'Mage', icon: '🔥', color: '#e0824f',
    difficulty: 'Normal',
    base: { hp: 860, attack: 148, defense: 63, speed: 91, critRate: 14, critDmg: 165 },
    description: 'Sets the battlefield ablaze and lets fire do the rest of the work.',
    strengths: ['Strong damage-over-time', 'Area denial'],
    weaknesses: ['Fragile', 'Slow to ramp'],
    passive: { name: 'Ignition', desc: 'Damage dealt to Burning targets is increased by 20%.' },
    basicAttack: { id: 'fire_bolt', name: 'Fire Bolt', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'burning_zone', name: 'Burning Zone', type: 'damage', targetType: 'middle_row', power: 1.0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'burn', duration: 2, chance: 70 }], desc: 'Burns the entire enemy Middle Row.' },
    skill2: { id: 'flame_burst', name: 'Flame Burst', type: 'damage', targetType: 'single_enemy', power: 1.5, cooldown: 2, energyGain: 15, desc: 'A concentrated burst of flame.' },
    ultimate: { id: 'inferno', name: 'Inferno', type: 'damage', targetType: 'all_enemy', power: 1.4,
      statuses: [{ id: 'burn', duration: 3, chance: 90 }], desc: 'Engulfs all enemies in a raging inferno.' },
  },
  {
    id: 'stormcaller', name: 'Stormcaller', role: 'Mage', icon: '⚡', color: '#e0e04f',
    difficulty: 'Hard',
    base: { hp: 840, attack: 152, defense: 60, speed: 100, critRate: 16, critDmg: 170 },
    description: 'Chains lightning across the enemy formation.',
    strengths: ['Multi-target chain damage', 'Good Speed for a Mage'],
    weaknesses: ['Low HP', 'Predictable targeting'],
    passive: { name: 'Static Charge', desc: 'Each hit landed builds a charge; at 3 charges the next Basic Attack deals +50% damage.' },
    basicAttack: { id: 'lightning_bolt', name: 'Lightning Bolt', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'chain_lightning', name: 'Chain Lightning', type: 'damage', targetType: 'all_enemy', power: 0.65, cooldown: 3, energyGain: 15, desc: 'Arcs lightning across all enemies.' },
    skill2: { id: 'thunder_strike', name: 'Thunder Strike', type: 'damage', targetType: 'single_enemy', power: 1.45, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'stun', duration: 1, chance: 25 }], desc: 'A heavy bolt with a chance to Stun.' },
    ultimate: { id: 'storm_apocalypse', name: 'Storm Apocalypse', type: 'damage', targetType: 'all_enemy', power: 1.6, desc: 'A cataclysmic storm over the battlefield.' },
  },
  {
    id: 'gunslinger', name: 'Gunslinger', role: 'Ranged', icon: '🔫', color: '#c9a24f',
    difficulty: 'Hard',
    base: { hp: 920, attack: 140, defense: 72, speed: 108, critRate: 24, critDmg: 175 },
    description: 'Manages a limited Ammo pool to unleash devastating volleys.',
    strengths: ['High crit rate', 'Burst windows after Reload'],
    weaknesses: ['Ammo-limited, weak when dry'],
    passive: { name: 'Quick Draw', desc: 'The first Basic Attack each battle is guaranteed to Critical Hit.' },
    basicAttack: { id: 'shoot', name: 'Shoot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'rapid_fire', name: 'Rapid Fire', type: 'damage', targetType: 'single_back', power: 1.3, cooldown: 2, energyGain: 20, desc: 'Headshot: two quick rounds aimed at the enemy Back Row.' },
    skill2: { id: 'reload', name: 'Reload', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 20,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }], desc: 'Reloads and boosts own Attack.' },
    ultimate: { id: 'bullet_storm', name: 'Bullet Storm', type: 'damage', targetType: 'all_enemy', power: 1.35, desc: 'Empties every chamber at the enemy team.' },
  },
  {
    id: 'beastmaster', name: 'Beastmaster', role: 'Summoner', icon: '🐾', color: '#a67c52',
    difficulty: 'Hard',
    base: { hp: 1020, attack: 128, defense: 84, speed: 96, critRate: 12, critDmg: 155 },
    description: "Commands a bonded beast that fights alongside her.",
    strengths: ['Consistent extra pressure', 'Flexible commands'],
    weaknesses: ['Weaker without beast active'],
    passive: { name: 'Animal Bond', desc: 'While her Beast Companion buff is active, her Basic Attacks deal +25% damage.' },
    basicAttack: { id: 'hunter_strike', name: 'Hunter Strike', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'summon_beast', name: 'Summon Beast', type: 'buff', targetType: 'self', power: 0, cooldown: 4, energyGain: 15,
      statuses: [{ id: 'beast_companion', duration: 3, chance: 100 }], desc: 'Summons a beast companion, boosting her own Attack.' },
    skill2: { id: 'command_beast', name: 'Command Beast', type: 'damage', targetType: 'single_enemy', power: 1.3, cooldown: 2, energyGain: 15, desc: 'Orders the beast to strike a target.' },
    ultimate: { id: 'primal_fury', name: 'Primal Fury', type: 'damage', targetType: 'all_enemy', power: 1.45, desc: 'She and her beast tear through the enemy line.' },
  },
  {
    id: 'guardian', name: 'Guardian', role: 'Tank', icon: '🏛️', color: '#7fa0c9',
    difficulty: 'Normal',
    base: { hp: 1300, attack: 100, defense: 140, speed: 65, critRate: 5, critDmg: 150 },
    description: 'An unbreakable wall who counters those foolish enough to strike him.',
    strengths: ['Highest Defense in the roster', 'Punishes attackers'],
    weaknesses: ['Lowest Speed', 'Low damage'],
    passive: { name: 'Unbreakable', desc: 'Damage taken is reduced by 10% whenever an ally has fallen.' },
    rowSynergy: { row: 'front', stat: 'defense', percent: 15, desc: '+15% Defense while positioned in the Front Row.' },
    basicAttack: { id: 'shield_strike', name: 'Shield Strike', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'fortify', name: 'Fortify', type: 'shield', targetType: 'self', power: 0.7, cooldown: 3, energyGain: 15, desc: 'Grants himself a heavy shield.' },
    skill2: { id: 'counter_guard', name: 'Counter Guard', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'counter_stance', duration: 2, chance: 100 }], desc: 'Reflects a portion of damage back at attackers.' },
    ultimate: { id: 'immortal_bastion', name: 'Immortal Bastion', type: 'shield', targetType: 'all_ally', power: 0.5, desc: 'Shields the entire team and taunts enemies.' },
  },
  {
    id: 'blood-knight', name: 'Blood Knight', role: 'Bruiser', icon: '🩸', color: '#a04058',
    difficulty: 'Hard',
    base: { hp: 1080, attack: 145, defense: 92, speed: 98, critRate: 14, critDmg: 165 },
    description: 'Fuels his blade with his own blood to grow stronger with every clash.',
    strengths: ['Self-sustain', 'Snowballs mid-fight'],
    weaknesses: ['Vulnerable early before stacks build'],
    passive: { name: 'Bloodlust', desc: 'Heals 20% of damage dealt by his Basic Attack.' },
    basicAttack: { id: 'blood_slash', name: 'Blood Slash', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'blood_drain', name: 'Blood Drain', type: 'damage', targetType: 'single_enemy', power: 1.2, cooldown: 2, energyGain: 15, drainPercent: 50, desc: 'Drains HP to heal himself.' },
    skill2: { id: 'crimson_rage', name: 'Crimson Rage', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }, { id: 'regeneration', duration: 2, chance: 100 }], desc: 'Boosts Attack and grants Regeneration.' },
    ultimate: { id: 'blood_apocalypse', name: 'Blood Apocalypse', type: 'damage', targetType: 'all_enemy', power: 1.5, drainPercent: 30, desc: 'A wide, life-draining strike.' },
  },
  {
    id: 'sky-lancer', name: 'Sky Lancer', role: 'Fighter', icon: '🪽', color: '#8fc9e0',
    difficulty: 'Normal',
    base: { hp: 1000, attack: 148, defense: 82, speed: 112, critRate: 18, critDmg: 168 },
    description: 'Strikes from above, diving past the front line to reach priority targets.',
    strengths: ['High mobility and Speed', 'Good damage vs backline'],
    weaknesses: ['Below-average bulk for a Fighter'],
    passive: { name: 'Aerial Mastery', desc: '+15% damage against the lowest-Defense enemy.' },
    basicAttack: { id: 'lance_strike', name: 'Lance Strike', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'sky_leap', name: 'Sky Leap', type: 'damage', targetType: 'single_enemy', power: 1.35, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'defense_down', duration: 2, chance: 60 }], desc: 'Leaps at a target, lowering its Defense.' },
    skill2: { id: 'dive_attack', name: 'Dive Attack', type: 'damage', targetType: 'single_back', power: 1.5, cooldown: 3, energyGain: 15, desc: 'Leaps past the Front Row to strike the enemy Back Row.' },
    ultimate: { id: 'heavens_spear', name: "Heaven's Spear", type: 'damage', targetType: 'all_enemy', power: 1.35, desc: 'Rains spears across the whole enemy team.' },
  },
  {
    id: 'necromancer', name: 'Necromancer', role: 'Summoner', icon: '☠️', color: '#6b8a6b',
    difficulty: 'Hard',
    base: { hp: 830, attack: 140, defense: 60, speed: 88, critRate: 10, critDmg: 160 },
    description: 'Raises the dead to overwhelm the enemy with numbers and decay.',
    strengths: ['Scales with fallen units on the field', 'Strong sustained damage'],
    weaknesses: ['Weak in the early turns'],
    passive: { name: 'Necrotic Power', desc: '+5% damage for every fallen character on the battlefield (either side).' },
    basicAttack: { id: 'dark_bolt_necro', name: 'Dark Bolt', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'summon_skeleton', name: 'Summon Skeleton', type: 'buff', targetType: 'self', power: 0, cooldown: 4, energyGain: 15,
      statuses: [{ id: 'attack_up', duration: 3, chance: 100 }], desc: 'Raises a skeleton, boosting his own Attack.' },
    skill2: { id: 'soul_drain', name: 'Soul Drain', type: 'damage', targetType: 'single_back', power: 1.25, cooldown: 2, energyGain: 15, drainPercent: 35, desc: 'Soul Curse: drains an enemy Back Row target to heal himself.' },
    ultimate: { id: 'army_of_the_dead', name: 'Army of the Dead', type: 'damage', targetType: 'all_enemy', power: 1.55,
      statuses: [{ id: 'attack_down', duration: 2, chance: 60 }], desc: 'Summons an army that overwhelms all enemies.' },
  },
  {
    id: 'druid', name: 'Druid', role: 'Hybrid', icon: '🌿', color: '#6fbf6f',
    difficulty: 'Normal',
    base: { hp: 1000, attack: 110, defense: 88, speed: 93, critRate: 10, critDmg: 155 },
    description: 'A nature warden who balances healing with punishing debuffs.',
    strengths: ['Flexible healer/controller hybrid', 'Sustained team support'],
    weaknesses: ['Low burst damage'],
    passive: { name: "Nature's Blessing", desc: 'Healing done is increased by 15%.' },
    basicAttack: { id: 'nature_strike', name: 'Nature Strike', type: 'damage', targetType: 'single_enemy', power: 0.9, energyGain: 10 },
    skill1: { id: 'regrowth', name: 'Regrowth', type: 'heal', targetType: 'single_ally', power: 1.3, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'regeneration', duration: 2, chance: 100 }], desc: 'Heals an ally and grants Regeneration.' },
    skill2: { id: 'entangling_roots', name: 'Entangling Roots', type: 'debuff', targetType: 'single_enemy', power: 0.5, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'root', duration: 1, chance: 75 }], desc: 'Roots a target in place.' },
    ultimate: { id: 'natures_wrath', name: "Nature's Wrath", type: 'heal', targetType: 'all_ally', power: 0.8,
      statuses: [{ id: 'regeneration', duration: 2, chance: 100 }], desc: 'Heals the team and grants lasting Regeneration.' },
  },
  {
    id: 'machinist', name: 'Machinist', role: 'Specialist', icon: '⚙️', color: '#c9c9a2',
    difficulty: 'Hard',
    base: { hp: 940, attack: 132, defense: 76, speed: 97, critRate: 15, critDmg: 160 },
    description: 'Deploys turrets and mines to control the flow of battle.',
    strengths: ['Battlefield control', 'Consistent chip damage'],
    weaknesses: ['Setup-dependent'],
    passive: { name: 'Engineering', desc: 'Skills have their cooldown reduced by 1 turn the first time they are used each battle.' },
    basicAttack: { id: 'pistol_shot', name: 'Pistol Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'deploy_turret', name: 'Deploy Turret', type: 'damage', targetType: 'single_enemy', power: 1.1, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'mark', duration: 2, chance: 80 }], desc: 'Deploys a turret that Marks the target.' },
    skill2: { id: 'land_mine', name: 'Land Mine', type: 'damage', targetType: 'all_enemy', power: 0.6, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'slow', duration: 2, chance: 60 }], desc: 'Plants mines that slow all enemies.' },
    ultimate: { id: 'mechanical_overload', name: 'Mechanical Overload', type: 'damage', targetType: 'all_enemy', power: 1.4,
      statuses: [{ id: 'stun', duration: 1, chance: 20 }], desc: 'Overloads all deployed devices at once.' },
  },

  // ===================== ROSTER EXPANSION: 21-30 =====================

  {
    id: 'paladin', name: 'Paladin', role: 'Tank', icon: '✝️', color: '#e8d98a',
    difficulty: 'Hard',
    base: { hp: 1260, attack: 92, defense: 122, speed: 75, critRate: 6, critDmg: 150 },
    description: 'A holy protector who steps between danger and the ally he has sworn to guard.',
    strengths: ['Redirects damage away from a chosen ally', 'Strong sustain', 'Can prevent one lethal hit'],
    weaknesses: ['Low damage', 'Low Speed', 'Weak if he has no ally left to protect'],
    passive: { name: "Guardian's Oath", desc: 'Each turn, automatically protects the lowest-HP living ally, redirecting a capped share of the damage they take to himself. Stronger in the Front Row, weaker in the Back Row.' },
    rowSynergy: { row: 'front', stat: 'defense', percent: 15, desc: '+15% Defense while positioned in the Front Row (protection is also strongest here).' },
    basicAttack: { id: 'holy_strike_pal', name: 'Holy Strike', type: 'damage', targetType: 'single_enemy', power: 0.95, energyGain: 10 },
    skill1: { id: 'holy_shield', name: 'Holy Shield', type: 'shield', targetType: 'single_ally', power: 0.55, cooldown: 3, energyGain: 15, desc: 'Shields an ally - stronger if they are his Protected Ally.' },
    skill2: { id: 'judgment', name: 'Judgment', type: 'damage', targetType: 'single_enemy', power: 1.15, cooldown: 2, energyGain: 15, desc: 'Deals bonus damage to debuffed targets; applies a short Defense Down if they carry 2+ debuffs.' },
    ultimate: { id: 'divine_intervention', name: 'Divine Intervention', type: 'heal', targetType: 'single_ally', power: 1.3,
      statuses: [{ id: 'divine_shield', duration: 3, chance: 100 }], desc: 'Restores HP and grants a ward that prevents one lethal hit, once.' },
  },
  {
    id: 'samurai', name: 'Samurai', role: 'Fighter', icon: '⚔️', color: '#c0392b',
    difficulty: 'Master',
    base: { hp: 1010, attack: 156, defense: 85, speed: 112, critRate: 20, critDmg: 175 },
    description: 'A duelist who reads the flow of battle and punishes anyone who strikes him.',
    strengths: ['Devastating counter-attacks', 'High single-target burst', 'Rewards good prediction'],
    weaknesses: ['Weak to AoE and DoT that bypass counters', 'Punished for guessing wrong', 'Poor if constantly crowd-controlled'],
    passive: { name: 'Bushido', desc: 'If Samurai is attacked while Defending, he immediately counter-attacks (once per turn).' },
    basicAttack: { id: 'katana_slash', name: 'Katana Slash', type: 'damage', targetType: 'single_enemy', power: 1.1, energyGain: 10 },
    skill1: { id: 'iaido', name: 'Iaido', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'iaido_stance', duration: 1, chance: 100 }], desc: 'Enters a stance: a powerful counter if struck before his next turn.' },
    skill2: { id: 'parry', name: 'Parry', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'parry_stance', duration: 1, chance: 100 }, { id: 'defense_up', duration: 1, chance: 100 }], desc: 'Sharply reduces incoming damage; a successful parry marks his next attack with bonus damage.' },
    ultimate: { id: 'final_cut', name: 'Final Cut', type: 'damage', targetType: 'single_enemy', power: 2.4,
      statuses: [{ id: 'attack_down', duration: 1, chance: 0 }], desc: 'A devastating strike with bonus damage vs low-HP or Marked targets. If it fails to kill, Samurai suffers a brief Defense Down.' },
  },
  {
    id: 'vampire', name: 'Vampire', role: 'Bruiser', icon: '🧛', color: '#7a1f3d',
    difficulty: 'Hard',
    base: { hp: 1130, attack: 150, defense: 88, speed: 96, critRate: 14, critDmg: 165 },
    description: 'A bloodthirsty fighter who grows harder to kill the longer the fight drags on.',
    strengths: ['Strong self-sustain on every hit', 'Scales well into long fights', 'High raw damage'],
    weaknesses: ['Vulnerable to anti-heal / healing reduction', 'Vulnerable to burst before he can stabilize', 'Vulnerable to crowd control'],
    passive: { name: 'Blood Feast', desc: 'Converts a portion of all damage he deals into HP (capped per hit so it can never spiral out of control).' },
    lifestealPercent: 16, lifestealCapPercentMaxHp: 8,
    basicAttack: { id: 'blood_claw', name: 'Blood Claw', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'crimson_bite', name: 'Crimson Bite', type: 'damage', targetType: 'single_enemy', power: 1.35, cooldown: 2, energyGain: 15, drainPercent: 30, desc: 'Bonus damage vs targets below 40% HP; heals on hit.' },
    skill2: { id: 'blood_frenzy_vamp', name: 'Blood Frenzy', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }, { id: 'blood_frenzy_def', duration: 2, chance: 100 }], desc: 'Gains Attack Up but suffers Defense Down.' },
    ultimate: { id: 'blood_moon', name: 'Blood Moon', type: 'damage', targetType: 'all_enemy', power: 1.35, desc: 'Damages every enemy and heals himself for a share of the total damage dealt - extra effect vs Bleeding targets.' },
  },
  {
    id: 'chronomancer', name: 'Chronomancer', role: 'Support', icon: '⏳', color: '#4fd1c5',
    difficulty: 'Master',
    base: { hp: 820, attack: 68, defense: 60, speed: 100, critRate: 8, critDmg: 150 },
    description: 'A time-weaver who manipulates the turn order itself rather than dealing damage.',
    strengths: ['Unique turn-order manipulation', 'Can undo recent damage on an ally', 'Great strategic utility'],
    weaknesses: ['Very low damage', 'Fragile', 'High-complexity kit', 'Vulnerable to burst and Silence'],
    passive: { name: 'Time Flow', desc: 'While in the Middle or Back Row, her turn-manipulation skills are slightly more effective.' },
    basicAttack: { id: 'time_bolt', name: 'Time Bolt', type: 'damage', targetType: 'single_enemy', power: 0.75, energyGain: 12 },
    skill1: { id: 'time_shift', name: 'Time Shift', type: 'special', targetType: 'single_ally', power: 0, cooldown: 3, energyGain: 15, desc: 'Advances an ally\'s action gauge, bringing their next turn closer (never grants an instant extra turn).' },
    skill2: { id: 'time_slow', name: 'Time Slow', type: 'debuff', targetType: 'single_enemy', power: 0.4, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'slow', duration: 2, chance: 80 }], desc: 'Slows a target; delays their action gauge further if their Ultimate is ready.' },
    ultimate: { id: 'rewind', name: 'Rewind', type: 'special', targetType: 'single_ally', power: 0, desc: "Restores an ally's HP to an earlier snapshot, restores some Energy, and cleanses a couple of debuffs. Cannot revive the fallen." },
  },
  {
    id: 'illusionist', name: 'Illusionist', role: 'Control', icon: '🎭', color: '#9b59b6',
    difficulty: 'Master',
    base: { hp: 830, attack: 122, defense: 62, speed: 99, critRate: 12, critDmg: 160 },
    description: 'A trickster who wins fights by making sure the enemy can never be quite sure what they are looking at.',
    strengths: ['Personal evasion', 'Can fully block incoming hits with a Decoy', 'Disrupts enemy targeting'],
    weaknesses: ['Low direct damage', 'Weak to AoE (which ignores single-target evasion tricks)', 'Weak to true/unavoidable damage'],
    passive: { name: 'Mirror Image', desc: 'A modest chance to fully evade an incoming attack (an illusion takes the hit instead).' },
    evasionPercent: 12,
    basicAttack: { id: 'arcane_mirror', name: 'Arcane Mirror', type: 'damage', targetType: 'single_enemy', power: 0.85, energyGain: 10 },
    skill1: { id: 'decoy', name: 'Decoy', type: 'buff', targetType: 'self', power: 0, cooldown: 4, energyGain: 10,
      statuses: [{ id: 'decoy_ward', duration: 3, chance: 100 }], desc: 'Conjures a decoy that fully blocks the next 2 hits, then grants Energy when it breaks.' },
    skill2: { id: 'confusion_cast', name: 'Confusion', type: 'debuff', targetType: 'single_enemy', power: 0.5, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'confusion', duration: 2, chance: 75 }], desc: 'The target may occasionally mis-target their next actions.' },
    ultimate: { id: 'grand_illusion', name: 'Grand Illusion', type: 'buff', targetType: 'all_ally', power: 0,
      statuses: [{ id: 'illusion_veil', duration: 2, chance: 100 }], desc: 'Wreathes the whole team in illusions, granting a temporary evasion window.' },
  },
  {
    id: 'alchemist', name: 'Alchemist', role: 'Specialist', icon: '⚗️', color: '#2ea55a',
    difficulty: 'Hard',
    base: { hp: 900, attack: 108, defense: 70, speed: 90, critRate: 10, critDmg: 155 },
    description: 'A field chemist who brews reagents mid-battle and combines them into powerful effects.',
    strengths: ['Very flexible toolkit', 'Adapts to what the team needs', 'Strong Ultimate when reagents are stocked'],
    weaknesses: ['Requires reagents to reach full power', 'Low direct damage', 'Some randomness in what she has available'],
    passive: { name: 'Transmutation', desc: 'Generates one random reagent (Healing, Toxic, Swift, or Purifying) at the start of each of her turns, up to a small stockpile.' },
    basicAttack: { id: 'alchemy_bolt', name: 'Alchemy Bolt', type: 'damage', targetType: 'single_enemy', power: 0.9, energyGain: 10 },
    skill1: { id: 'healing_potion', name: 'Healing Potion', type: 'heal', targetType: 'single_ally', power: 1.2, cooldown: 2, energyGain: 15, desc: 'Consumes a Healing Reagent for a strong heal (reduced potency if none is stocked).' },
    skill2: { id: 'toxic_flask', name: 'Toxic Flask', type: 'damage', targetType: 'single_enemy', power: 0.9, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'poison', duration: 3, chance: 85 }], desc: 'Consumes a Toxic Reagent for damage plus a strong Poison (reduced potency if none is stocked).' },
    ultimate: { id: 'forbidden_mixture', name: 'Forbidden Mixture', type: 'special', targetType: 'self', power: 0, desc: 'Combines every reagent she has on hand into a powerful combined effect - still works, just weaker, if her stockpile is low.' },
  },
  {
    id: 'duelist', name: 'Duelist', role: 'Assassin', icon: '🤺', color: '#34495e',
    difficulty: 'Hard',
    base: { hp: 880, attack: 152, defense: 70, speed: 106, critRate: 20, critDmg: 175 },
    description: 'A single-target specialist who grows deadlier the longer she duels the same rival.',
    strengths: ['Excellent sustained single-target damage', 'Counter-attacks a marked rival', 'Punishes an isolated target hard'],
    weaknesses: ['Poor against multiple targets', 'Loses her stacks if forced to switch targets', 'Weak to crowd control chains'],
    passive: { name: 'Challenger', desc: 'Gains a stack (up to 3) each time she hits the same target consecutively, each stack adding bonus damage against them. Switching targets resets the stacks.' },
    basicAttack: { id: 'rapid_slash', name: 'Rapid Slash', type: 'damage', targetType: 'single_enemy', power: 1.05, energyGain: 10 },
    skill1: { id: 'challenge', name: 'Challenge', type: 'debuff', targetType: 'single_enemy', power: 0.7, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'duel_mark', duration: 3, chance: 100 }], desc: 'Marks a rival, locking in bonus damage against them.' },
    skill2: { id: 'riposte', name: 'Riposte', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10,
      statuses: [{ id: 'counter_stance', duration: 2, chance: 100 }], desc: 'If her Marked rival attacks her while this is active, she counters.' },
    ultimate: { id: 'final_duel', name: 'Final Duel', type: 'damage', targetType: 'single_enemy', power: 1.9,
      statuses: [{ id: 'duel_mark', duration: 3, chance: 100 }], desc: 'Challenges a rival to a duel: heavy damage, and both combatants hit harder against each other for a few turns.' },
  },
  {
    id: 'pirate_captain', name: 'Pirate Captain', role: 'Ranged', icon: '🏴‍☠️', color: '#8b5e3c',
    difficulty: 'Normal',
    base: { hp: 960, attack: 138, defense: 76, speed: 98, critRate: 16, critDmg: 165 },
    description: 'A cannon-wielding raider who marks targets for elimination and rearranges the battlefield with brute force.',
    strengths: ['Strong AoE', 'Can physically reposition enemies', 'Bonus damage vs Marked targets'],
    weaknesses: ['Needs a turn of setup for full value', 'Moderate single-target damage without a Mark'],
    passive: { name: 'Wanted', desc: 'Deals bonus damage against any target carrying his Wanted Mark.' },
    basicAttack: { id: 'pistol_shot_pirate', name: 'Pistol Shot', type: 'damage', targetType: 'single_enemy', power: 1.0, energyGain: 10 },
    skill1: { id: 'marked_shot', name: 'Marked Shot', type: 'debuff', targetType: 'any_enemy', power: 0.5, cooldown: 2, energyGain: 15,
      statuses: [{ id: 'wanted_mark', duration: 3, chance: 100 }], desc: 'Slaps a Wanted Mark on any enemy, prioritizing the Back Row.' },
    skill2: { id: 'explosive_barrel', name: 'Explosive Barrel', type: 'damage', targetType: 'front_row', power: 0.85, cooldown: 3, energyGain: 15, desc: 'Blasts the enemy Front Row and knocks survivors back a row (Front -> Middle).' },
    ultimate: { id: 'broadside', name: 'Broadside', type: 'damage', targetType: 'all_enemy', power: 1.4, desc: 'A full cannon salvo on the enemy formation, with bonus damage against the Wanted target.' },
  },
  {
    id: 'spirit_shaman', name: 'Spirit Shaman', role: 'Summoner', icon: '🪶', color: '#5dade2',
    difficulty: 'Master',
    base: { hp: 940, attack: 98, defense: 75, speed: 92, critRate: 8, critDmg: 150 },
    description: 'A totem-caller whose team-wide auras shift depending on which spirit she has bonded with.',
    strengths: ['Strong team utility', 'Flexible totem strategy', 'Solid team-wide Ultimate'],
    weaknesses: ['Low direct damage', 'Only one Totem can be active at a time', 'Requires setup to get full value'],
    passive: { name: 'Spirit Bond', desc: 'Only one Totem aura can be active for the team at a time - casting a new Totem replaces the old one.' },
    basicAttack: { id: 'spirit_bolt', name: 'Spirit Bolt', type: 'damage', targetType: 'single_enemy', power: 0.85, energyGain: 10 },
    skill1: { id: 'healing_totem', name: 'Healing Totem', type: 'special', targetType: 'all_ally', power: 0, cooldown: 4, energyGain: 15, desc: 'Grants the whole team Regeneration for a few turns (replaces the Spirit Totem if active).' },
    skill2: { id: 'spirit_totem', name: 'Spirit Totem', type: 'special', targetType: 'all_ally', power: 0, cooldown: 4, energyGain: 15, desc: 'Grants the whole team a Speed boost for a few turns (replaces the Healing Totem if active).' },
    ultimate: { id: 'ancestral_spirits', name: 'Ancestral Spirits', type: 'buff', targetType: 'all_ally', power: 0,
      statuses: [{ id: 'attack_up', duration: 2, chance: 100 }, { id: 'defense_up', duration: 2, chance: 100 }, { id: 'regeneration', duration: 2, chance: 100 }], desc: 'Calls on the ancestors to empower the whole team at once.' },
  },
  {
    id: 'gravity_mage', name: 'Gravity Mage', role: 'Mage', icon: '🕳️', color: '#4b3f72',
    difficulty: 'Master',
    base: { hp: 820, attack: 138, defense: 60, speed: 90, critRate: 12, critDmg: 160 },
    description: 'A formation-breaker who bends gravity to drag enemies out of position.',
    strengths: ['Powerful position manipulation', 'Strong against rigid formations', 'Good AoE control'],
    weaknesses: ['Low single-target burst', 'Fragile', 'Weak against high-Speed assassins who can reach her first'],
    passive: { name: 'Gravity Field', desc: 'Her hits leave enemies slightly heavier - a small Speed penalty that lingers briefly.' },
    basicAttack: { id: 'gravity_bolt', name: 'Gravity Bolt', type: 'damage', targetType: 'single_enemy', power: 0.85, energyGain: 10,
      statuses: [{ id: 'gravity_weight', duration: 1, chance: 40 }] },
    skill1: { id: 'gravity_pull', name: 'Gravity Pull', type: 'debuff', targetType: 'single_back', power: 0.75, cooldown: 3, energyGain: 15, desc: 'Damages a Back Row target and hauls them one row forward (no movement if already in Front).' },
    skill2: { id: 'gravity_crush', name: 'Gravity Crush', type: 'damage', targetType: 'middle_row', power: 0.9, cooldown: 3, energyGain: 15,
      statuses: [{ id: 'slow', duration: 2, chance: 70 }], desc: 'Crushes the enemy Middle Row with damage and Slow.' },
    ultimate: { id: 'singularity', name: 'Singularity', type: 'damage', targetType: 'adjacent_enemies', power: 1.3,
      statuses: [{ id: 'slow', duration: 2, chance: 80 }], desc: 'Creates a singularity that pulls nearby enemies together, damaging and slowing all of them - the more it catches, the harder it hits.' },
  },
];

// Training Dummy: not part of the selectable roster (CHARACTERS array), used only
// by Practice and Character Test modes as a stationary, weak sparring partner.
const TRAINING_DUMMY = {
  id: 'training-dummy', name: 'Training Dummy', role: 'Specialist', icon: '🎯', color: '#666a70',
  difficulty: 'Easy',
  base: { hp: 2000, attack: 60, defense: 60, speed: 60, critRate: 5, critDmg: 150 },
  description: 'A stuffed practice target. Deals minimal damage and never uses skills strategically.',
  strengths: ['High HP - survives long test sessions'], weaknesses: ['Very low damage', 'No real strategy'],
  passive: { name: 'Inanimate', desc: 'No passive effect.' },
  basicAttack: { id: 'dummy_swing', name: 'Wobble', type: 'damage', targetType: 'single_enemy', power: 0.7, energyGain: 10 },
  skill1: { id: 'dummy_skill1', name: 'Creak', type: 'damage', targetType: 'single_enemy', power: 0.8, cooldown: 2, energyGain: 15, desc: 'A weak strike.' },
  skill2: { id: 'dummy_skill2', name: 'Wobble Harder', type: 'buff', targetType: 'self', power: 0, cooldown: 3, energyGain: 10, statuses: [{ id: 'defense_up', duration: 2, chance: 100 }], desc: 'Braces itself.' },
  ultimate: { id: 'dummy_ultimate', name: 'Stuffing Burst', type: 'damage', targetType: 'single_enemy', power: 1.2, desc: 'Releases stuffing in a weak burst.' },
};

// Shared defend action (identical mechanics for every character, applied by combat engine)
const DEFEND_ACTION = {
  id: 'defend', name: 'Defend', type: 'defend',
  damageReduction: 40, energyGain: 8,
};

function getCharacterById(id) {
  return CHARACTERS.find(c => c.id === id) || null;
}
